### ISSUE TITLE
depth=1 on google cloud storage is broken when folder has same prefix as existing object

### ISSUE THREAD

**Issue by davidovich** [helm/chartmuseum#113]
consider the following storage structure:

```
[bucket]/my-project-root-chart.tgz
[bucket]/my-project/my-project-a-chart.tgz
```

getting an index in that structure will fail with 
```
{
    error: "storage: object doesn't exist"
}
```

After investigation, this is related to the fact that listing objects in the backend with `my-project` prefix will return a list of [my-project-root-chart.tgz, my-project-a-chart.tgz] which is wrong. Then, to build the index, we fetch `my-project-root-chart.tgz` in the `my-project/` folder which is not found. The server fails.

Note that this behavior will maybe crop up in other object storage implementations.

**Comment by jdolitsky** [comment]
@davidovich can this be solved by simply making sure prefix ends with a "/" char?
