### ISSUE TITLE
Remote values file injected at helm install

### ISSUE THREAD

**Issue by mumrau** [helm/chartmuseum#143]
Hello everyone,

That issue might be related to Helm itself, but it could be a chartmuseum issue too, and I wanna apologize if I missed something crucial.

I set up my repository and I got it fully working except for one thing (which might not be supported), let's suppose the chart I wanna deploy is really abstract in the sense that it is versatile depending on provided values file.
I cannot deploy that chart with one of the several values file in my remote chart folder (alongside Charts.yaml), even though it is packaged inside the chart archive that I can retrieve using helm fetch.

EDIT: I just noticed that #2642 in kubernetes/helm (https://github.com/kubernetes/helm/issues/2642) referenced that possibility, I just find it pretty strange that you would have to link remote files while they were already in the cahrt archive.
Nonetheless, chartmuseum maybe could serve those values vile in a new route in order to comply with that?

Regards.

**Comment by jdolitsky** [comment]
@Mumrau welcome, thanks for opening

This seems to be the same ask as chartmuseum #88 . Can you confirm?

**Comment by Mumrau** [comment]
Yes kind of.
I would rather have a special route in order for values because this is one
of core concept but yes this is the same objective.
I didn't find it during my research because I only saw it valuable for
"values" instead of "files".
