### ISSUE TITLE
ChartMuseum UI

### ISSUE THREAD

**Issue by jdolitsky** [helm/chartmuseum#150]
As a ChartMuseum user, I want a basic UI so that I can:

- **Login with basic auth credentials (if enabled)**
- **List all charts in repo**
- **List all versions of a chart**
- **Download charts**
- **Upload charts**
- **Delete charts**
- Search for charts
- Display the chart's README (see #88, #143)
- Mark my repo as public vs private

In the case that I am running a large multi-tenant ChartMuseum install (depth=2), I should be able to:

- Login via third-party (see #59)
- Create new organizations
- Create new repos
- Assign various roles to my team members, such as:
  - member/admin of an organization
  - ability to view/administer a repo
  - ability to create/read/update/delete charts to/from a specific repo

---

The items in **bold** above are able to be implemented *today* (with ChartMuseum v0.7.1). The other items require significant changes on the server-side to support, and should be discussed in detail.

Please comment here with any other desired functionality.

**Comment by obeyler** [comment]
May you can use Monocular to do that  it's an helm chart repository browser. It can help you to show what is present into your chartmuseum. I don't know if you can use it to push new chart into your chartmseum repos.

**Comment by jdolitsky** [comment]
This was just published: https://github.com/idobry/chartmuseumui

**Comment by jdolitsky** [comment]
The above repo is now an official chartmuseum project: https://github.com/chartmuseum/ui
