### ISSUE TITLE
authentication issue

### ISSUE THREAD

**Issue by equaqin** [helm/chartmuseum#156]
I can set the username and password in yaml file and when upload chart tgz to chartmusem it requires authentication. Does it support multiple username and password? And currently the password is cleartext in the configuration yaml, could there be some way to hide the cleartext password?

**Comment by mattfarina** [comment]
@equaqin Work is being done to enable a better authentication system. This will likely leverage external providers and use a common mechanism. It's currently under development.

**Comment by gsexton** [comment]
@mattfarina I looked through the code and saw that there is support for doing bearer auth. Are there any docs out there the show how to do this? I admit, I've never done this kind of auth before. Are there any specific auth servers that chartmuseum is known to work with?

**Comment by jdolitsky** [comment]
@gsexton the bearer auth support is still in progress, and will be more supported in 0.8.0 release

Please take a look at this in the meantime:
https://github.com/chartmuseum/auth-server-example
