### ISSUE TITLE
Absolute url in the string "url"

### ISSUE THREAD

**Issue by kirrbr** [helm/chartmuseum#170]
how to make the string from
urls:
    - charts/mariadb-3.0.3.tgz
to
urls:
    - https://privatecharts.test.com/mariadb-5.0.5.tgz

Rancher 2.0 is not working because of the following issue:
https://github.com/rancher/rancher/issues/13788

Thanks

**Comment by jdolitsky** [comment]
@kirrbr hello, please try using --chart-url=<url>

**Comment by kirrbr** [comment]
Thanks @jdolitsky . It worked

**Comment by chris-aeviator** [comment]
> @kirrbr hello, please try using --chart-url=

could you please show the full command, I can't find the param in helm doc (by searching it)
