### ISSUE TITLE
HA setup - Consistency issue when pushing new charts

### ISSUE THREAD

**Issue by born4new** [helm/chartmuseum#175]
## Our setup

We have installed Chartmuseum with the Helm chart on Kubernetes with an S3 backend and no caching mechanism.

We set the replica **to 2** for the deployment.

## Failing scenario

* We push a new package successfully.
* If we go check the index page on the api (`/api/charts`), the newly pushed package is not there.
* If we push again, we get an error from chartmuseum that the chart has already been pushed.

## The solution?

* We set the replica **to 1**.
* Immediately after that, the new chart was visible on the api (`/api/charts`).

## Our suspicions

There is some caching in chartmuseum's pods that prevent from hitting the S3 backend again when displaying the index...

**Comment by jdolitsky** [comment]
@born4new I've just tried to replicate this by standing up two local servers on two separate ports, pointing to the same backend. I push to one server, and afterwards do a `GET /api/charts` on the other one and the package is there.

If possible, could you share some logs coming from the pods linked to the /api/charts request?

**Comment by echoboomer** [comment]
> @born4new can you also try using `DISABLE_STATEFILES=true` in values.yaml?

FWIW this resolved our issue. We were running into random failures to pull a version, confirmed tested in the API. The chart package was in the bucket, but one `Pod` would randomly fail to find it. Setting this option to `true` fixed the issue.

**Comment by r0kas** [comment]
I've just tried running HA and no it doesn't work properly in HA setup.
Index is not being regenerated in second replica when new chart is pushed. DISABLE_STATEFILES=true option did not help either.
We use GCP storage bucket for persistence layer.

**Comment by SimplicityGuy** [comment]
We're hitting consistency issues with 3 replicas in a cluster, with s3 as the backing store. We backed down to 1 replica for now to avoid the inconsistent results, but clearly this is not how we want to operate CM for the long term.

**Comment by mkhpalm** [comment]
HA doesn't work for us either when publishing new charts with `0.15.0` using local storage (shared posix filesystem). `DISABLE_STATEFILES=true` does not help though I did verify the yaml stopped being generated. Second replica never looks at the filesystem to update its own in-memory index

Only option I could find was to scale it to 1.

FWIW, this all used to work fine on chartmuseum 0.11.0

**Comment by scbizu** [comment]
I wrote the proposal of the fixup in #545 , I need more community sounds about the proposal  if possible .

And lets talk about the HA setup in https://github.com/helm/chartmuseum/issues/148.

**Comment by alexvaque** [comment]
> @born4new I've just tried to replicate this by standing up two local servers on two separate ports, pointing to the same backend. I push to one server, and afterwards do a `GET /api/charts` on the other one and the package is there.
> 
> If possible, could you share some logs coming from the pods linked to the /api/charts request?

Hi @born4new , I am trying to create an HA but in my case I am using 3 different K8S clusters with different Chartmuseums endpoints (mirror1, mirror2, mirror3) but we are using the same S3 bucket, Is that possible to do in chartmuseum ? Will we have some race condition issue ? thanks
