### ISSUE TITLE
Can you guys release 0.7.2?

### ISSUE THREAD

**Issue by ralekseenkov** [helm/chartmuseum#181]
We'd like to take advantage of "--force". But it's not in 0.7.1 and switching our Helm-based deployment to use the "latest" docker image doesn't sound like a good idea.

**Comment by jdolitsky** [comment]
@ralekseenkov Hi. We are planning a 0.8.0 release that will be ready soon, thanks for your patience

**Comment by jdolitsky** [comment]
@ralekseenkov 0.8.0 is now released!
