### ISSUE TITLE
high latency

### ISSUE THREAD

**Issue by ekjuanrejon** [helm/chartmuseum#184]
Hello 

I am running chartmuseum connected to azure blob but the latency to query index.yaml is very high.

What can I do to remedy the situation?

**Comment by jdolitsky** [comment]
@ekjuanrejon can you elaborate? Can you send output of `time helm repo add myrepo <url>`? How many charts do you have in storage? Is everything running in the same region?

**Comment by ekjuanrejon** [comment]
Hello 

attached is an image of the logs. The blob is in region EU and chartmuseum running in Australia region

![image](https://user-images.githubusercontent.com/38057696/47981468-ec26a400-e0c3-11e8-8559-17f33613351c.png)

**Comment by ekjuanrejon** [comment]
Hello

I put everything under the same region and is fast
