### ISSUE TITLE
404 not found if calling /:repo/index.yaml when :repo=api

### ISSUE THREAD

**Issue by steven-zou** [helm/chartmuseum#201]
* set depth=1
* use repo name `api`

404 not found error will be returned when calling index.yaml of repo **api** ` /:repo/index.yaml (/api/index.yaml)` because the request will be identified as an API request. However, there is no API handler to handle it.

**Comment by jdolitsky** [comment]
@steven-zou im not sure what to do in this case. Due to current API design, `/api` detected at the root signifies an API route. This issue may also apply to a repo named `/health`.

The best solution I can think of at this time is to add to the documentation that "api" and "health" are invalid repo names. Another way this can be resolved is using and extra depth layer as a vanity prefix, for example "r" (DEPTH=2):

```
/r/api/index.yaml
/r/otherrepo/index.yaml
```

Do you have another solution in mind? Without changing the API design?

**Comment by steven-zou** [comment]
@jdolitsky 

Thanks for the response. I don't think using the `DEPTH=2` can resolve the issue because `/r/api/index.yaml` will still be parsed as API route which no handler to handle it (actually I have tested that scenario before submitting this issue, it does not work). Additionally, `DEPTH=2` breaks our design, we only need to enable `DEPTH=1`.

IMO, the `api` should particularly/explicitly be handled for the `index.yaml` request before passing to the API handlers. (I have no other good idea, so far)

**Comment by nlowe** [comment]
I believe we're seeing this as well (also using harbor) with a project called `api-design`.

**Comment by jdolitsky** [comment]
@steven-zou @nlowe ok, we should get this resolved soon. At the very least, only "api" should be whitelisted, not anything with api as a prefix (e.g. api-design, apixel, etc)

**Comment by jdolitsky** [comment]
@steven-zou @nlowe @petvaa01 this should be fixed in master/latest. Can somebody help test the `latest` Docker image with Harbor? Once verified I can cut a new release.

**Comment by nlowe** [comment]
It looks like harbor uses a custom docker image. I'll see if I can get one built and tested this week.

**Comment by nlowe** [comment]
It seems the chartmuseum repo has changed significantly since Harbor last pulled a version in. I was able to hack our build scripts to make a new image and test this out.

The good news is this seems to have fixed searching searching for images in harbor, I can browse projects that have `api` in their name again.

However, trying to list charts for a project in harbor respond with an error (Harbor 500's because chartmuseum 404's), same deal for uploading charts. Here's a snippet from chartmuseum's logs:

```txt
Apr 11 11:54:53 172.30.0.1 chartmuseum[1129]: {"L":"WARN","T":"2019-04-11T15:54:53.033Z","M":"[563] Request served","path":"/api/nlowe/charts","comment":"","latency":"70.908µs","clientIP":"192.168.0.4","method":"GET","statusCode":404,"reqID":"556efd7b-15b9-49a7-bc2a-abbb1a8db07a"}
Apr 11 11:54:53 172.30.0.1 chartmuseum[1129]: {"L":"WARN","T":"2019-04-11T15:54:53.050Z","M":"[564] Request served","path":"/api/nlowe/charts","comment":"","latency":"50.731µs","clientIP":"192.168.0.4","method":"GET","statusCode":404,"reqID":"28e88997-f9ce-4ff6-b200-b55ec22ed3a7"}
Apr 11 11:57:22 172.30.0.1 chartmuseum[1129]: {"L":"WARN","T":"2019-04-11T15:57:22.006Z","M":"[570] Request served","path":"/api/nlowe/charts","comment":"","latency":"97.655µs","clientIP":"10.34.6.76","method":"POST","statusCode":404,"reqID":"7fc12a26-1ce1-4ca3-b4c1-103519defed7"}
Apr 11 11:57:22 172.30.0.1 chartmuseum[1129]: {"L":"WARN","T":"2019-04-11T15:57:22.031Z","M":"[571] Request served","path":"/api/nlowe/charts","comment":"","latency":"67.676µs","clientIP":"192.168.0.4","method":"GET","statusCode":404,"reqID":"17153e69-43c4-431d-8ea5-48978e806969"}
```

Should harbor be using the `/api` prefix for these requests? If not that's definitely a harbor bug.

**Comment by jdolitsky** [comment]
@nlowe you're using a version based on chartmueum latest/master? The requests look correct. The format should be `/api/<repo>/charts`. It comes down to the `DEPTH`/`--depth` configuration being used, which I'm not sure how to configure via Harbor. According to earlier post by Steven, it's always supposed to use DEPTH=1, which should result in /api/nlowe/charts being valid.

Another thing that might be going on is the API is disabled via `--disable-api`/`DISABLE_API=true`

**Comment by nlowe** [comment]
Indeed it is disabled: 

```bash
sh-4.4# env
MAX_STORAGE_OBJECTS=0
DEPTH=1
ALLOW_OVERWRITE=true
INDEX_LIMIT=0
HOSTNAME=33c3d61e2ef1
DEBUG=false
CACHE_REDIS_DB=3
CHART_POST_FORM_FIELD_NAME=chart
CACHE=redis
STORAGE=local
PWD=/
TLS_KEY=
HOME=/root
BASIC_AUTH_USER=chart_controller
STORAGE_LOCAL_ROOTDIR=/chart_storage
DISABLE_METRICS=false
DISABLE_API=true
...
```

Let me see if this was leftover from my hacking on it weeks ago or if this is how harbor always deploys it.

**Comment by nlowe** [comment]
That fixed it! I was able to upload a chart and get a chart listing!

**Comment by jdolitsky** [comment]
@nlowe great to hear. thank you for verifying. Will try to push out a release within the next week. Thanks for your patience!

**Comment by steven-zou** [comment]
> @nlowe great to hear. thank you for verifying. Will try to push out a release within the next week. Thanks for your patience!

@jdolitsky 

Josh, when will the release be ready? We're looking forward to it to fix the issue from our users ^_^.

**Comment by jdolitsky** [comment]
@steven-zou working on, to be available near future. please follow #254

**Comment by jdolitsky** [comment]
@nlowe @steven-zou 0.9.0 version has been released, thank you for your patience :)
