### ISSUE TITLE
Add example that using minio as backend in document

### ISSUE THREAD

**Issue by pytimer** [helm/chartmuseum#202]
Hi, all

I using `minio` as a backend, like S3. However, [using-with-amazon-s3](https://github.com/helm/chartmuseum#using-with-amazon-s3) section in README.md describe not very clearly. 

Is it add description how to using `minio` as a backend? Such as setting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

**Comment by jdolitsky** [comment]
@pytimer yes good point, should be documented.

Please see this thread: https://github.com/helm/chartmuseum/issues/162

It basically comes down to using the `--storage-amazon-endpoint` option

**Comment by pytimer** [comment]
@jdolitsky Thank for your reponse. 

I am willing to do it if necessary, maybe my English is not good.
