### ISSUE TITLE
Error: 404: could not properly parse response JSON: default backend - 404 Error: plugin "push" exited with error

### ISSUE THREAD

**Issue by trimbleAdam** [helm/chartmuseum#210]
Got back from the weekend, and am now seeing this error on the client side. Turned on debug and there is nothing interesting in the chartmuseum logs.

Can someone please provide me with a direction to get to the bottom of this?

k8s version: 1.11
chartmuseum version: tried both v0.7.1 (worked Friday) and 0.8.1 this morning, both have the same problem.

Any help is greatly appreciated!

**Comment by jdolitsky** [comment]
@trimbleAdam it is likely that the upload API is disabled, please see this thread: https://stackoverflow.com/a/48731728

**Comment by trimbleAdam** [comment]
Thanks for the quick response!
I actually do have that flag set to true.

My formula for deploying this (has worked until today...) has been fetching the chart from stable, and customizing values.yaml as follows:
`
replicaCount: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
image:
  repository: chartmuseum/chartmuseum
  tag: v0.8.1
  pullPolicy: Always
env:
  open:
    # storage backend, can be one of: local, alibaba, amazon, google, microsoft
    STORAGE: amazon
    # oss bucket to store charts for alibaba storage backend
    STORAGE_ALIBABA_BUCKET:
    # prefix to store charts for alibaba storage backend
    STORAGE_ALIBABA_PREFIX:
    # oss endpoint to store charts for alibaba storage backend
    STORAGE_ALIBABA_ENDPOINT:
    # server side encryption algorithm for alibaba storage backend, can be one
    # of: AES256 or KMS
    STORAGE_ALIBABA_SSE:
    # s3 bucket to store charts for amazon storage backend
    STORAGE_AMAZON_BUCKET: REDACTED
    # prefix to store charts for amazon storage backend
    STORAGE_AMAZON_PREFIX: ""
    # region of s3 bucket to store charts
    STORAGE_AMAZON_REGION: REDACTED
    # alternative s3 endpoint
    STORAGE_AMAZON_ENDPOINT:
    # server side encryption algorithm
    STORAGE_AMAZON_SSE:
    # gcs bucket to store charts for google storage backend
    STORAGE_GOOGLE_BUCKET:
    # prefix to store charts for google storage backend
    STORAGE_GOOGLE_PREFIX:
    # container to store charts for microsoft storage backend
    STORAGE_MICROSOFT_CONTAINER:
    # prefix to store charts for microsoft storage backend
    STORAGE_MICROSOFT_PREFIX:
    # container to store charts for openstack storage backend
    STORAGE_OPENSTACK_CONTAINER:
    # prefix to store charts for openstack storage backend
    STORAGE_OPENSTACK_PREFIX:
    # region of openstack container
    STORAGE_OPENSTACK_REGION:
    # path to a CA cert bundle for your openstack endpoint
    STORAGE_OPENSTACK_CACERT:
    # form field which will be queried for the chart file content
    CHART_POST_FORM_FIELD_NAME: chart
    # form field which will be queried for the provenance file content
    PROV_POST_FORM_FIELD_NAME: prov
    # levels of nested repos for multitenancy. The default depth is 0 (singletenant server)
    DEPTH: 0
    # show debug messages
    DEBUG: true
    # output structured logs as json
    LOG_JSON: true
    # disable use of index-cache.yaml
    DISABLE_STATEFILES: false
    # disable Prometheus metrics
    DISABLE_METRICS: true
    # disable all routes prefixed with /api
    DISABLE_API: false
    # allow chart versions to be re-uploaded
    ALLOW_OVERWRITE: true
    # absolute url for .tgzs in index.yaml
    CHART_URL:
    # allow anonymous GET operations when auth is used
    AUTH_ANONYMOUS_GET: false
    # sets the base context path
    CONTEXT_PATH:
    # parallel scan limit for the repo indexer
    INDEX_LIMIT: 0
    # cache store, can be one of: redis (leave blank for inmemory cache)
    CACHE:
    # address of Redis service (host:port)
    CACHE_REDIS_ADDR:
    # Redis database to be selected after connect
    CACHE_REDIS_DB: 0
  field:
    # POD_IP: status.podIP
  secret:
    # username for basic http authentication
    BASIC_AUTH_USER:
    # password for basic http authentication
    BASIC_AUTH_PASS:
    # GCP service account json file
    GOOGLE_CREDENTIALS_JSON:
    # Redis requirepass server configuration
    CACHE_REDIS_PASSWORD:
  # Name of an existing secret to get the secret values ftom
  existingSecret:
  # Stores Enviromnt Variable to secret key name mappings
  existingSecretMappings:
    # username for basic http authentication
    BASIC_AUTH_USER:
    # password for basic http authentication
    BASIC_AUTH_PASS:
    # GCP service account json file
    GOOGLE_CREDENTIALS_JSON:
    # Redis requirepass server configuration
    CACHE_REDIS_PASSWORD:

deployment:
  ## Chartmuseum Deployment annotations
  annotations: {}
  #   name: value
  labels: {}
  #   name: value
  matchlabes: {}
  #   name: value
replica:
  ## Chartmuseum Replicas annotations
  annotations: {}
  ## Read more about kube2iam to provide access to s3 https://github.com/jtblin/kube2iam
  #   iam.amazonaws.com/role: role-arn
service:
  servicename:
  type: ClusterIP
  # clusterIP: None
  externalPort: 8080
  nodePort:
  annotations: {}
  labels: {}

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 80m
#    memory: 64Mi

probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

serviceAccount:
  create: false
  # name:

# UID/GID 1000 is the default user "chartmuseum" used in
# the container image starting in v0.8.0 and above. This
# is required for local persistant storage. If your cluster
# does not allow this, try setting securityContext: {}
securityContext:
  fsGroup: 1000

nodeSelector:
  vss/application:
    jenkins

tolerations: []

affinity: {}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi
  labels: {}
  #   name: value
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## Chartmuseum data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  # volumeName:
  pv:
    enabled: false
    pvname:
    capacity:
      storage: 8Gi
    accessMode: ReadWriteOnce
    nfs:
      server:
      path:

## Ingress for load balancer
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: REDACTED
  hosts:
    chartmuseum.REDACTED:
        - /charts
        - /index.yaml

## Chartmuseum Ingress TLS configuration
## Secrets must be manually created in the namespace
##
#   tls:
#   - secretName: chartmuseum-server-tls
#     hosts:
#     - chartmuseum.domain.com

# Adding secrets to tiller is not a great option, so If you want to use an existing
# secret that contains the json file, you can use the following entries
gcp:
  secret:
    enabled: false
    # Name of the secret that contains the encoded json
    name:
    # Secret key that holds the json value.
    key: credentials.json

`

Again, this was a pretty simple deployment, and it starting acting funny just today.

I truly appreciate your looking into this with me.

Adam

**Comment by trimbleAdam** [comment]
Interestingly, even though I've manually specified this API_ACCESS parameter, the value is not found in the pod ENV:

```
adaught-us-la:mirror adaught$ kc exec -it chartmuseum-chartmuseum-8655697657-h2jh7 sh
/ $ env
CHARTMUSEUM_CHARTMUSEUM_PORT_8080_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://172.20.0.1:443
CHARTMUSEUM_CHARTMUSEUM_PORT=tcp://172.20.14.191:8080
CHARTMUSEUM_CHARTMUSEUM_SERVICE_PORT=8080
HOSTNAME=chartmuseum-chartmuseum-8655697657-h2jh7
SHLVL=1
ALLOW_OVERWRITE=true
HOME=/home/chartmuseum
CHARTMUSEUM_CHARTMUSEUM_PORT_8080_TCP=tcp://172.20.14.191:8080
TERM=xterm
LOG_JSON=true
KUBERNETES_PORT_443_TCP_ADDR=172.20.0.1
CHART_POST_FORM_FIELD_NAME=chart
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
STORAGE_AMAZON_BUCKET=REDACTED
STORAGE=amazon
CHARTMUSEUM_CHARTMUSEUM_SERVICE_PORT_HTTP=8080
PROV_POST_FORM_FIELD_NAME=prov
KUBERNETES_PORT_443_TCP=tcp://172.20.0.1:443
KUBERNETES_SERVICE_PORT_HTTPS=443
STORAGE_AMAZON_REGION=REDACTED
KUBERNETES_SERVICE_HOST=172.20.0.1
PWD=/
DISABLE_METRICS=true
CHARTMUSEUM_CHARTMUSEUM_PORT_8080_TCP_ADDR=172.20.14.191
CHARTMUSEUM_CHARTMUSEUM_SERVICE_HOST=172.20.14.191
CHARTMUSEUM_CHARTMUSEUM_PORT_8080_TCP_PORT=8080
```

...and as you pointed out, just fetching http://chartmuseum.my.org.com/api/charts also return 404.

**Comment by trimbleAdam** [comment]
Could this be a helm version issue? I just upgraded to 2.12.3 recently...

**Comment by trimbleAdam** [comment]
Forcibly stuff DISABLE_API into deployment and still not working:

```
kubectl describe deployment
...
Environment:
      ALLOW_OVERWRITE:             true
      DISABLE_API:                 false
...

kubectl describe rs
...
Environment:
      ALLOW_OVERWRITE:             true
      DISABLE_API:                 false
...

kubectl describe po
...
Environment:
      ALLOW_OVERWRITE:             true
      DISABLE_API:                 false
...
```

**Comment by jdolitsky** [comment]
@trimbleAdam is the DNS maybe pointing to the wrong service? Can you try running a `curl localhost:8080/api/charts` inside the container?

**Comment by trimbleAdam** [comment]
Okay, after getting a one-off Dockerfile set up and curl added, I can see the expected response from curl localhost:8080/api/charts.

Something about the service+ingress must be badly mangled.

**Comment by trimbleAdam** [comment]
What just worked:

I removed the absolute paths under the ingress.hosts map and left only / and things are working again.

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: REDACTED
  hosts:
    chartmuseum.REDACTED:
        - /
```

It is very curious to my as to why this is now this way, but either way thanks for the help!

Adam
