### ISSUE TITLE
HTTP HEAD requests return 404

### ISSUE THREAD

**Issue by vngzs** [helm/chartmuseum#212]
I would like to be able to call, mirroring the readme,

```
HEAD /charts/mychart-0.1.0.tgz
```

in order to determine the presence of a chart without actually getting it. Instead, when doing this for a chart that is present, chartmuesum returns 404.

**Comment by jdolitsky** [comment]
@vngzs thanks for opening. This should be pretty easy to implement

**Comment by cbwest3-ntnx** [comment]
@jdolitsky, it appears this issue is not resolved. HTTP HEAD now works for /api/charts due to #277, but does not work for fetching TGZs. Is it best to reopen this issue or create a new one? Thanks!
