### ISSUE TITLE
ChartMuseum - Delete Chart returns not found

### ISSUE THREAD

**Issue by quadrinho** [helm/chartmuseum#215]
We try to delete some chart on chartmuseum but we receive:

{"error":"not found"}

curl -X DELETE https://chartmuseum-devscrum.cpaas-accenture.com/charts/software-manager/7.3.8-SNAPSHOT

The chart is present in Chart Museum:

         "name":"software-manager",
         "version":"7.3.8-SNAPSHOT",
         "description":"Helm chart for Software-Manager installation on Kubenetes",
         "apiVersion":"v1",
         "urls":[
            "https://chartmuseum-devscrum.cpaas-accenture.com/charts/software-manager-7.3.8-SNAPSHOT.tgz"

Which is the problem?

Thanks

**Comment by jdolitsky** [comment]
@quadrinho problem solved? API disabled?

**Comment by quadrinho** [comment]
Hi,

yes! i forgot "api" in the url.

Thanks!

Alessio

**Comment by jdolitsky** [comment]
👍
