### ISSUE TITLE
CodeFresh CI checks don't seem to be running for pull requests.

### ISSUE THREAD

**Issue by tariq1890** [helm/chartmuseum#229]
Although there is a YAML file for PR checks [here](https://github.com/helm/chartmuseum/blob/02e6cc72bfa4ffdf041dc879a7aab64bb1a2f256/.codefresh/pr.yml), it doesn't look like it has been enabled.

**Comment by jdolitsky** [comment]
It seems that they are running, but not giving the checkmark on the PRs.. will look into it.

For now can view the PR pipeline queue: https://g.codefresh.io/public/accounts/chartmuseum/pipelines/5c0aa531144012a62fef87a1

**Comment by jdolitsky** [comment]
@olegsu @dustinvanbuskirk can one of you take a look at the issue with this trigger if/when you have a few min?

**Comment by jdolitsky** [comment]
This now fixed
