### ISSUE TITLE
curl --data-binary "Permission Denied"

### ISSUE THREAD

**Issue by gfpa88** [helm/chartmuseum#231]
Hi, I am using chartmuseum i'm trying to upload my chart but gives me "permission denied"

helm start with docker

`
docker run --rm -it
  -p 3000:8080
  -e DEBUG=1
  -e STORAGE=local
  -e STORAGE_LOCAL_ROOTDIR=/charts
  -e DISABLE_API=false
  -v $(pwd)/charts:/charts
  chartmuseum/chartmuseum:latest
`

When i run:
`
$ curl --data-binary "@aaa-0.0.1.tgz" http://xx.xx.xx.xx:3000/api/charts
`
I got:
`{"error":"open /charts/gravitee-0.0.1.tgz: permission denied"}
`

The logs in container are:

DEBUG   Fetching chart list from storage        {"repo": ""}
DEBUG   No change detected between cache and storage    {"repo": ""}

INFO    Starting ChartMuseum    {"port": 8080}
DEBUG   [1] Incoming request: /api/charts       {"reqID": "9daa6e9b-d8d1-4552-adde-d3f264d10ef4"}
DEBUG   [1] Adding package to storage   {"package": "aaa-0.0.1.tgz", "reqID": "9daa6e9b-d8d1-4552-adde-d3f264d10ef4"}

 ERROR   [1] Request served      {"path": "/api/charts", "comment": "", "latency": "7.316665ms", "clientIP": "xxxxxxx", "method": "POST", "statusCode": 500, "reqID": "9daa

**Comment by jdolitsky** [comment]
@gfpa88 Hi there. It seems some permission issue on the file `gravitee-0.0.1.tgz` that is already located in the `charts/` dir. Could you try creating a new dir, such as `test/` then try
```
-v $(pwd)/test:/charts 
```
?

The try the curl again?

**Comment by gfpa88** [comment]
> @gfpa88 Hi there. It seems some permission issue on the file `gravitee-0.0.1.tgz` that is already located in the `charts/` dir. Could you try creating a new dir, such as `test/` then try
> 
> ```
> -v $(pwd)/test:/charts 
> ```
> 
> ?
> 
> The try the curl again?

**Comment by gfpa88** [comment]
@jdolitsky 

Is the same....

**Comment by jdolitsky** [comment]
Instead of :/charts can you please try :/home/chartmuseum/charts ?

Maybe an issue w the container user, which is now “chartmuseum” (was
previously root)

**Comment by gfpa88** [comment]
Now it works but without the volume, like this:

docker run --rm -it \
  -p 3000:8080 \
  -e DEBUG=1 \
  -e STORAGE=local \
  -e STORAGE_LOCAL_ROOTDIR=/home/chartmuseum/charts \
  -e DISABLE_API=false \
  chartmuseum/chartmuseum:latest

But when I run with thr volume option, it keeps return permission denied. The folders in the host became write protected. 

Example:
 docker run --rm -it \
  -p 3000:8080 \
  -e DEBUG=1 \
  -e STORAGE=local \
  -e STORAGE_LOCAL_ROOTDIR=/home/chartmuseum/charts \
  -e DISABLE_API=false \
  -v $(pwd)/test:/home/chartmuseum/charts \
  chartmuseum/chartmuseum:latest

**Comment by gfpa88** [comment]
Finally, I get this to work,

I had to create the volume folders in the host before run the docker command.

Thanks

**Comment by jdolitsky** [comment]
Great to hear!
