### ISSUE TITLE
the problem about the auth service

### ISSUE THREAD

**Issue by pingf** [helm/chartmuseum#240]
I‘ve been digging into the bearer token auth scenario， just found that  in 
 this page https://github.com/chartmuseum/auth-server-example
```
Www-Authenticate: Bearer realm="http://localhost:5001/oauth/token",service="localhost:5001",scope="artifact-repository:org1/repo1:pull"
```

from my personal understanding， here the service should be something represent the chartmuseum itself, not auth server, the auth server will use it to identify different chat museum (so it should not be the address for the auth server).

so it should be sth. like

```
Www-Authenticate: Bearer realm="http://localhost:5001/oauth/token",service="chartmuseum",scope="artifact-repository:org1/repo1:pull"
```

**Comment by hzpfly** [comment]
Hi pingf,
I have also tried to run the example. The service is not used by Chartmuseum or auth-server-example in authentication process. So I think the value can be any string. 
BRs
Michael

**Comment by jdolitsky** [comment]
@pingf @hzpfly so is the issue just in the auth example and how it is used?

**Comment by pingf** [comment]
@jdolitsky yep, i think so
