### ISSUE TITLE
Allow disabling the DELETE route

### ISSUE THREAD

**Issue by davidovich** [helm/chartmuseum#243]
Presently, if the API is enabled, this also gives a user the DELETE permission globally. This can be a problem in multi-tenant installations as other tenants get the right to delete charts arbitrarily from other tenants.

We should decouple the DELETE route from the `APIEnabled` setting, in the same spirit as we allow controlling overwrites.

**Comment by jdolitsky** [comment]
@davidovich sounds good to me - this is also true of uploading charts to other tenants. access can be limited w token auth
