### ISSUE TITLE
Can not delete chart

### ISSUE THREAD

**Issue by jianzzz** [helm/chartmuseum#253]
1. use index-cache.yaml
2. use storage.backend: amazon
3. call DELETE /api/charts/<name>/<version>, return true
4. call GET /api/charts, still list the deleted one
5. check backend storage, package is deleted, but  index-cache.yaml still holds the index
6. the deleted one is named xxx-yyy-01-0.1.0.tgz

How can I fix this problem?

**Comment by jianzzz** [comment]
anyone to answer this question?

**Comment by jdolitsky** [comment]
@jianzzz sorry for delay here. this appear to be a duplicate of #261, lets continue discussion there
