### ISSUE TITLE
Feature request: Bind to a specific IP address

### ISSUE THREAD

**Issue by nfam** [helm/chartmuseum#255]
**Use case**: I have chartmuseum run natively on my laptop (not in docker machine). However, from what I see, chartmuseum listens to all available network interfaces, thus any machine in the same wifi is able to access to my chartmuseum.

**Expect**: an argument in CLI to specify which network interface, aka. IP, to bind to.

**Comment by spigell** [comment]
I need this feature also. +1

**Comment by CoolDuke** [comment]
I want chartmuseum to listen on the loopback device to deploy an Nginx in front of it and prohibiting access to chartmuseum directly.

My current workaround is setting up a firewall rule via systemd unit file right before chartmuseum starts:
```
ExecStartPre=+/bin/bash -c "(iptables -L | grep 8443) || iptables -I INPUT -p tcp --dport 8443 ! -s 127.0.0.1 -j REJECT --reject-with=tcp-reset"
ExecStart=/usr/local/bin/chartmuseum --port 8443 [...]
```
