### ISSUE TITLE
Cannot delete cache if chart name contains hyphen immediately followed a digital

### ISSUE THREAD

**Issue by ninjadq** [helm/chartmuseum#261]
If chart name contains hyphen immediately followed by a digit(like the pattern `xxx-1x`, will cause unable to delete the cache of that name problem.

Because after you delete a chart version `xxx-1x-0.0.1` there is no `xxx-1x-0.0.1` object on disk anymore.

Next time when regeneration repo index the chart name and version will lose in [this](https://github.com/helm/chartmuseum/blob/d4a4cf6ff101caf2e8a0aa6d06dc251f0221fd94/pkg/chartmuseum/server/multitenant/index.go#L103) transformation

It results that chartmuseum can only guess the chart name. But  [this line](https://github.com/helm/chartmuseum/blob/d4a4cf6ff101caf2e8a0aa6d06dc251f0221fd94/pkg/repo/chart.go#L108) it's not enough to determine a chartname.

So `RemoveEntry` cannot find the right entry name to remove the cache. then the removed object file will regenerate again.

**Comment by jianzzz** [comment]
> If chart name contains hyphen immediately followed by a digit(like the pattern `xxx-1x`, will cause unable to delete the cache of that name problem.
> 
> Because after you delete a chart version `xxx-1x-0.0.1` there is no `xxx-1x-0.0.1` object on disk anymore.
> 
> Next time when regeneration repo index the chart name and version will lose in [this](https://github.com/helm/chartmuseum/blob/d4a4cf6ff101caf2e8a0aa6d06dc251f0221fd94/pkg/chartmuseum/server/multitenant/index.go#L103) transformation
> 
> It results that chartmuseum can only guess the chart name. But [this line](https://github.com/helm/chartmuseum/blob/d4a4cf6ff101caf2e8a0aa6d06dc251f0221fd94/pkg/repo/chart.go#L108) it's not enough to determine a chartname.
> 
> So `RemoveEntry` cannot find the right entry name to remove the cache. then the removed object file will regenerate again.

Do you have any idea to fix this problem?

**Comment by jdolitsky** [comment]
Hi, thanks for detailed description.

A quick fix for this is top change pattern for versioning. I believe something like `<name>-<semver>-nonnumerical` would work. It is difficult to determine from the filename alone the name+version if it is not formatted exactly as `<name>-<version>.tgz`

A longer term solution is probably needed to better determine chart version from filename

**Comment by duyanghao** [comment]
@jdolitsky why not use last part of `-` as version directly? That means version field could contain any character except `-`.

**Comment by jdolitsky** [comment]
@duyanghao versions in helm do sometimes contain a "-" character is the problem. For example "1.0.0-rc1"

If anybody has a solution for this, PRs are certainly welcome

**Comment by duyanghao** [comment]
@jdolitsky I have created a [PR](https://github.com/helm/chartmuseum/pull/268) to solve this conflict, and the core concept is that `Parse chart Version backwards until a field starting with 'digest' is found`.

**Comment by jdolitsky** [comment]
@duyanghao please test with latest docker image:

```
$ docker run chartmuseum/chartmuseum:latest -v
ChartMuseum version 0.9.0 (build cd845be)
```

If you can verify, we will cut a new release

**Comment by duyanghao** [comment]
> @duyanghao please test with latest docker image:
> 
> ```
> $ docker run chartmuseum/chartmuseum:latest -v
> ChartMuseum version 0.9.0 (build cd845be)
> ```
> 
> If you can verify, we will cut a new release

@jdolitsky Verify successfully as below:
```
# test Scenario 1
# curl --data-binary "@mychart-0.1.0.tgz" http://localhost:4040/api/charts                    
{"saved":true}
# curl http://localhost:4040/api/charts                                    
{"mychart":[{"name":"mychart","version":"0.1.0","urls":["charts/mychart-0.1.0.tgz"],"created":"2019-09-10T02:15:59.652746307Z","digest":"e3f74f42dd6f9654baa103e746d18b275c9562a4743fb7aa91db0654bea691dc"}]}
# curl -X "DELETE" http://localhost:4040/api/charts/mychart/0.1.0
{"deleted":true}
# curl http://localhost:4040/api/charts                           
{}
# test Scenario 2
# curl --data-binary "@mychart-1x-0.1.0.tgz" http://localhost:4040/api/charts                      
{"saved":true}
# curl http://localhost:4040/api/charts                                     
{"mychart-1x":[{"name":"mychart-1x","version":"0.1.0","urls":["charts/mychart-1x-0.1.0.tgz"],"created":"2019-09-10T02:22:22.403736375Z","digest":"065f076b18483bf8896eb08fd84ad07e48e80cc825ecc26f4b5b6cc973d54b89"}]}
# curl -X "DELETE" http://localhost:4040/api/charts/mychart-1x/0.1.0  
{"deleted":true}
# curl http://localhost:4040/api/charts                            
{}
```

**Comment by jdolitsky** [comment]
@duyanghao thank you for checking this. will put together a release early next week 👍

**Comment by piyush94** [comment]
@jdolitsky This issue is happening for me with chartmuseum v12 and with chart version like 0.1.0-SNAPSHOT-24.
Is this versioning scheme incompatible with chartmuseum ?
