### ISSUE TITLE
Is it possible to limit results returned by accessing /api/charts?

### ISSUE THREAD

**Issue by YoninL** [helm/chartmuseum#270]
We have a lot of charts, would like to have some query strings like ?limit=15&offset=0 for paging, can we add this support? Thanks.

**Comment by jdolitsky** [comment]
@YoninL This is currently supported, but we would gladly accept a PR for this. Is the limit on charts or chart versions (i.e one chart may have 100 versions)

**Comment by YoninL** [comment]
For me currently it's only for charts, but you're right, both may need to take into consideration. Do you have any good ideas?

**Comment by jdolitsky** [comment]
@YoninL we could use `chartlimit`, `chartoffset`, `versionlimit`, `versionoffset`. What are your numbers looking like? Lots of charts or lots of chart versions?

**Comment by YoninL** [comment]
Good idea, we have around 100 charts, but only one version for each for now, for the implementation/pr, I'm afraid I don't have time now.

**Comment by prabhu43** [comment]
@jdolitsky @YoninL  I will work on this and raise PR
