### ISSUE TITLE
DELETE curl failed

### ISSUE THREAD

**Issue by longlg88** [helm/chartmuseum#281]
I use chartmuseum v0.8.1(deploy in kubernetes cluster for chart version chartmuseum-1.9.0).
It can see my app's chart version this command
p.s. [CHARTMUSEUM URL] [APP NAME] --> couldn't expose our service..  sorry for that

`curl -s [CHARTMUSEUM URL]/api/charts/[APP NAME] | jq -r '.[].version`
Then the result example is this.
```
v0.0.1-20190129-1145-stable
v0.0.1-20190129-1145
```

I try to curl -s X DELETE for deleting chart.
`curl -s -X DELETE [CHARTMUSEUM URL]/api/charts/[APP NAME]/v0.0.1-20190129-1145-stable`
Then the result is this.
```
{"deleted": true}
```

But check list one more time, then the result is this.
```
v0.0.1-20190129-1145-stable
v0.0.1-20190129-1145
```

I try to DELETE curl once more.
`curl -s -X DELETE [CHARTMUSEUM URL]/api/charts/[APP NAME]/v0.0.1-20190129-1145-stable`
Then the message is this.
```
{"error":"remove /storage/[APP NAME]-v0.0.1-20190129-1145-stable.tgz: no such file or directory"}
```

I don't know what's the problem is

**Comment by longlg88** [comment]
Anybody there?

**Comment by shreben** [comment]
Hi @jdolitsky 
I also fell into an issue while trying to delete a chart. I'm using chartmuseum `v0.11`, aws s3 as a backend. I'm able to push and pull/fetch charts, but face a weird behavior while trying to delete a chart.
`GET` request:
```
$ curl http://.../api/charts/demo-service
[{"name":"demo-service","home":"https://...","sources":["https://..."],"version":"2.1.331-SNAPSHOT", ...
```
Corresponding chartmuseum log entry:
```
2020-01-31T10:11:05.703557476Z {"L":"DEBUG","T":"2020-01-31T10:11:05.703Z","M":"[144] Incoming request: /api/charts/demo-service","reqID":"5a55e8537b94edb6ed93ef6dc019d0d3"}
2020-01-31T10:11:05.7036106Z {"L":"DEBUG","T":"2020-01-31T10:11:05.703Z","M":"[144] Entry found in cache store","repo":"","reqID":"5a55e8537b94edb6ed93ef6dc019d0d3"}
2020-01-31T10:11:05.703617378Z {"L":"DEBUG","T":"2020-01-31T10:11:05.703Z","M":"[144] Fetching chart list from storage","repo":"","reqID":"5a55e8537b94edb6ed93ef6dc019d0d3"}
2020-01-31T10:11:05.858181556Z {"L":"DEBUG","T":"2020-01-31T10:11:05.856Z","M":"[144] No change detected between cache and storage","repo":"","reqID":"5a55e8537b94edb6ed93ef6dc019d0d3"}
2020-01-31T10:11:05.858281767Z {"L":"INFO","T":"2020-01-31T10:11:05.856Z","M":"[144] Request served","path":"/api/charts/demo-service","comment":"","latency":"153.102829ms","clientIP":"10.18.250.75","method":"GET","statusCode":200,"reqID":"5a55e8537b94edb6ed93ef6dc019d0d3"}
```

`DELETE` request:
```
$ curl -XDELETE http:/.../api/charts/demo-service/2.1.331-SNAPSHOT
{"error":"AccessDenied: Access Denied\n\tstatus code: 403, request id: 8D436D7CFA9D0075, host id: 2QnxzY6BZhvQoLC1xMgVUzjSlmS5xA7w+s3Xb8JFs83Xnv/4TRFUAbHG2Eihk07Cv4M4K1QS7qA="}
```
Corresponding chartmuseum log entry:
```
2020-01-31T10:12:12.785895883Z {"L":"DEBUG","T":"2020-01-31T10:12:12.785Z","M":"[167] Incoming request: /api/charts/demo-service/2.1.331-SNAPSHOT","reqID":"90f26868b92f8f82b169d1ffc7c7f332"}
2020-01-31T10:12:12.785932967Z {"L":"DEBUG","T":"2020-01-31T10:12:12.785Z","M":"[167] Deleting package from storage","package":"demo-service-2.1.331-SNAPSHOT.tgz","reqID":"90f26868b92f8f82b169d1ffc7c7f332"}
2020-01-31T10:12:12.924924464Z {"L":"WARN","T":"2020-01-31T10:12:12.924Z","M":"[167] Request served","path":"/api/charts/demo-service/2.1.331-SNAPSHOT","comment":"","latency":"138.97171ms","clientIP":"10.18.250.75","method":"DELETE","statusCode":404,"reqID":"90f26868b92f8f82b169d1ffc7c7f332"}
```

Could you please point out what could went wrong?

**Comment by jopfeffe** [comment]
@longlg88 i'm facing the same issue. Have you found any solution yet?

**Comment by longlg88** [comment]
@jopfeffe Not yet... I think we should find where this error occured. :(

**Comment by longlg88** [comment]
@shreben @jopfeffe  Guys, I found a little strange thing.
I tested like this.
```
App name : sample-web
App version : v0.1.0

App name : sample-web
App version : v0.1.2

App name : sample-web
App version : v0.1.3-20200211
```
App version v0.1.0 and v0.1.2 can be deleted,  but v0.1.3-20200211 can't be deleted.
So We should find why charts doesn't delete in chart list because of special characters

**Comment by longlg88** [comment]
pkg/chartmuseum/server/multitenant/routes.go

```
if s.APIEnabled && !s.DisableDelete {
		routes = append(routes, &cm_router.Route{"DELETE", "/api/:repo/charts/:name/:version", s.deleteChartVersionRequestHandler, cm_auth.PushAction})
	}
```
Delete API will action here

**Comment by jopfeffe** [comment]
In my case i noticed that the actual file is in fact deleted from the S3 storage but the index.yaml isn't updated. In the logs it says it updated the index.yaml (and the cache one) but the it still contains the file reference.

**Comment by longlg88** [comment]
@jopfeffe You're exactly right. I find location which error is occured.

```
chartmuseum/pkg/chartmuseum/server/multitenant/cache.go

...
func (server *MultiTenantServer) removeIndexObject(log cm_logger.LoggingFn, repo string, index *cm_repo.Index, object cm_storage.Object) error {
	chartVersion, err := server.getObjectChartVersion(repo, object, false)
	if err != nil {
		return server.checkInvalidChartPackageError(log, repo, object, err, "removed")
	}
	log(cm_logger.DebugLevel, "Removing chart from index",
		"repo", repo,
		"name", chartVersion.Name,
		"version", chartVersion.Version,
	)
	index.RemoveEntry(chartVersion)
	return nil
}
...
```

removeIndexObject function is very weird.

My debug output is this.
```
2020-02-11T07:57:25.246Z	DEBUG	[13] Removing chart from index	{"repo": "", "name": "pycharm-remote-builder-v0.1.3", "version": "stable", "reqID": "8366adfb-c7eb-441c-bea6-7aea0f03edaf"}
2020-02-11T07:57:25.246Z	DEBUG	[13] Removing chart from index	{"repo": "", "name": "pycharm-remote-builder-v0.1.3-20200211", "version": "0313", "reqID": "8366adfb-c7eb-441c-bea6-7aea0f03edaf"}
```

**Comment by longlg88** [comment]
At Last!!!
This function makes confusing us.
`chartmuseum/pkg/repo/chart.go`

```
func emptyChartVersionFromPackageFilename(filename string) *helm_repo.ChartVersion {
	noExt := strings.TrimSuffix(pathutil.Base(filename), fmt.Sprintf(".%s", ChartPackageFileExtension))
	parts := strings.Split(noExt, "-")
	lastIndex := len(parts) - 1
	name := parts[0]
	version := ""

	for idx := lastIndex; idx >= 1; idx-- {
		if _, err := strconv.Atoi(string(parts[idx][0])); err == nil { // see if this part looks like a version (starts w int)
			version = strings.Join(parts[idx:], "-")
			name = strings.Join(parts[:idx], "-")
			break
		}
	}
	if version == "" { // no parts looked like a real version, just take everything after last hyphen
		name = strings.Join(parts[:lastIndex], "-")
		version = parts[lastIndex]
	}

	metadata := &helm_chart.Metadata{Name: name, Version: version}
	return &helm_repo.ChartVersion{Metadata: metadata}
}
```
The order what we were doing is this.
1. helm push images
2. Using GET method to list chart
3. Using DELETE method chart
4. Using GET method to list chart

As a result, we shouldn't add '-' in version.
example) "name": "sample-name", "version": "v0.0.1" OK
                "name": "sample-name", "version": "v0.0.1-stable" FAIL
                "name": "sample-name", "version": "v0.0.1-20200211-stable" FAIL
                "name": "sample-name", "version": "v0.0.1+stable" OK

**Comment by jopfeffe** [comment]
I am not familiar with go programming, but I could imagine that the problem is located in this function.
https://github.com/helm/chartmuseum/blob/969515a51413e1f1840fb99509401aa3c63deccd/pkg/repo/chart.go#L102

It says: 
`// see if this part looks like a version (starts w int)`

But also something like "1.2.3-alpha.1" is also a valid version.
https://semver.org/spec/v2.0.0.html

**Comment by longlg88** [comment]
@jopfeffe You're right.

But the chartmuseum doesn't support that kind of version because name and version split based on last dash('-').

Although the version is exactly right that you said because of sementic versioning, chartmuseum get wrong version...

**Comment by longlg88** [comment]
Guys.
There is a same issue in chartmuseum.

Check this out.
https://github.com/helm/chartmuseum/issues/22

And i close this issue.
