### ISSUE TITLE
Why no new releases? :/

### ISSUE THREAD

**Issue by karuppiah7890** [helm/chartmuseum#286]
I see some good features in the new commits. And two new major versions of helm have come. I'm planning to bump it through this issue #285 . I'm hoping to see some releases 😅 so that people can fix some problems like https://github.com/helm/helm/issues/6849 which needs `helm repo index` to create a proper index yaml file. I need to check how that works in chartmusem, but in any case, I just wanted to ask why no releases? 😢  Just curious. Also, I do know there's a lot of attention to the OCI registry feature of Helm 3 and push charts to registries as an alternative to chartmuseum. But for now, I think lots of Helm 2 users exist, and that will be the case for sometime, so I think it's worth it to maintain and release chartmuseum.

Also, a funny meme for "Why you no release?"

![why-no](https://user-images.githubusercontent.com/12808424/68988329-78cd7b80-085b-11ea-8fc1-c4a66f3f7578.png)

ccing @jdolitsky The Releaser 😉

**Comment by jdolitsky** [comment]
@karuppiah7890 you make a good point its been a while! No reason inparticular, just other work and life stuff taking priority.

Will work on getting out a `v0.10` soon.

**Comment by jdolitsky** [comment]
v0.10.0 has been released!
