### ISSUE TITLE
Permission denied when adding a chart.

### ISSUE THREAD

**Issue by chainhead** [helm/chartmuseum#305]
Any particular reason for using `chartmuseum` as the user? This does not work well when running in OpenShift where the mounted volume is created with `root` user. Therefore, chart upload fails with a permission denied message.

**Comment by jdolitsky** [comment]
@chainhead hello, please see the origins of this: https://github.com/helm/chartmuseum/issues/166

**Comment by chainhead** [comment]
My aim is to mount a `PersistentVolumeClaim` as the storage option on a Kubernetes cluster. The volume gets mounted with `root:root` ownership. Since `chartmuseum` is running under the `chartmuseum` user ID, it does not have access to the mounted volume. Therefore, uploading of charts fails due to permission errors.

I will have to edit the default `Dockerfile` to enable access.
