### ISSUE TITLE
Provide version in info endpoint

### ISSUE THREAD

**Issue by HungUnicorn** [helm/chartmuseum#309]
I would like to see the current version of chartmuseum in one endpoint, e.g., /info, and Documentation should add the following:

### Server Info
`GET /info:` - returns current version

**Comment by Dean-Coakley** [comment]
@jdolitsky Are you open to accepting a PR for this?

**Comment by jdolitsky** [comment]
@Dean-Coakley sure - I think itd be best if this returned structured JSON such as `{"version": "0.12.0"}` so we can add more fields to it
