### ISSUE TITLE
Update chart using the same version

### ISSUE THREAD

**Issue by danilorsilva** [helm/chartmuseum#313]
Hello all,

     Is there a way to update my chart and use the same version?

     For example: i changed the docker image version and would like to update my chart and keep the same version.

Thanks!

**Comment by jdolitsky** [comment]
@danilorsilva Yes, you can run chartmuseum with the `--allow-overwrite` option, or add `?force=true` to URL querystring on upload

Closing for now, if still need help, please re-open
