### ISSUE TITLE
proposal: museum should always check the upload chart version

### ISSUE THREAD

**Issue by scbizu** [helm/chartmuseum#320]
Hi, there !

## Background

1. Helm only support the valid `semver 2 version` chart .
2. But chartmuseum allows the non-semantic chart , and the chart cannot be downloaded from remote museum , it will be the museum garbage  until we found it and delete it manually . 

## Proposal 

It is better if we can  do some semantic version checking when users upload their chat .

Well , as for details , we should add validate code before we `PutObject` into the backend storage:

```go
	version,err:=cm_repo.ChartVersionFromStorageObject(storage.Object{
		Content: content,
	})

	sem,err:= semver.Parse(version.Metadata.Version)
	if err!=nil {
		// handle error msg
	}

	if !sem.Validate(){
		// return invalid chart version
	}
```  

Leave  me the message  if you need the PR .

**Comment by jdolitsky** [comment]
Hello, if you can add this via PR as configurable option that would be great. Maybe `--enforce-semver`?
