### ISSUE TITLE
Latency value from Chartmuseum logs

### ISSUE THREAD

**Issue by pgdagenais** [helm/chartmuseum#321]
Hey all,

The `latency` value (for example `latency: 520.816056ms`) returned by the logs still has the units in it's string, which when ingested in Elasticsearch cause some conflicts (string vs int) with others go software that write the `latency` values with a int type.

I know that I could use some mapping within Kibana to modify the values of the logs to a int.
But mainly this issue is more of a proposal instead of a issue with the software.

Proposal: Modifying [this](https://github.com/helm/chartmuseum/blob/master/pkg/chartmuseum/router/middleware.go#L55) line to this: `"latency", int64(time.Now().Sub(start)),`

One of the main drawbacks of changing it from a string to a int is that it is _less_ human readable.

I'm happy to create a PR if you guys agree with this. If not you can just close this issue.

Thanks

**Comment by jdolitsky** [comment]
@pgdagenais thanks for opening. Would love if you're willing to PR this. I'd probably ask to have it behind a configuration flag so as not to affect people relying on current format. Maybe something like `--log-latency-integer`

**Comment by pgdagenais** [comment]
Awesome I will try to work on that!

Thanks for the quick answer.

**Comment by pgdagenais** [comment]
Hey @jdolitsky, my co-worker was able to work on the issue, please see the linked pull request

**Comment by jdolitsky** [comment]
@pgdagenais thanks for notifying me - just merged! Should be available on `chartmuseum/chartmuseum:latest` if you want to try

**Comment by pgdagenais** [comment]
Awesome we will try for sure thanks!
