### ISSUE TITLE
Performance downgrade when dealing with thousands of charts

### ISSUE THREAD

**Issue by stainboy** [helm/chartmuseum#332]
## Background
In our use case, it's easy to generate thousands of charts within couple weeks because CI/CD pipeline is integrated with hundreds of GitHub repositories and each pipeline run generates one chart.

Per observation, **It takes more than 10s to response any API (e.g. `GET /api/charts/<name>`) if there are about 5000 charts.**. Performance downgrade is dramatic and unacceptable. Especially when working together with Harbor, it makes the call to harbor frequently fail due to a fixed timeout interval (10s in this case).

## Analysis
All the `GET` requests call function `getIndexFile()`, which searches all the chart files from storage and updates the cache for `index.yaml` regardless whether the cache exists or not. It performs slower and slower with the growth of chart numbers. Although consistency and real-time are guaranteed, cache seems don't work at all.

## Proposal
To solve the problem and improve the performance, the only way is to make the cache "work" as expected. Therefore, I recommend to apply the following changes,
- Always read from cache in function `getIndexFile()` without traversing the files on the disk. If cache is missing, rebuild it
- Delta update the cache in all the WRITE requests (e.g. `POST /api/charts` or `DELETE /api/charts/<name>/<version>`)
- Delta update the cache every 5min (in case the files on the disk are manually manipulated)

A PR will be provided to fix the issue in 2 weeks. Hope some one from the governance team can review and accept it.

**Comment by scbizu** [comment]
May the auto-purge will be helpful in your case ? If so , here is a help-wanted issue: https://github.com/helm/chartmuseum/issues/316

**Comment by jdolitsky** [comment]
@stainboy thanks for detailed report, few things:

1. If you can help with improving caching and performance in chartmuseum via PR, it would be greatly appreciated by many
2. Helm 3.0+ has now experimental support for registries, which are a better long term solution for helm charts storage performance (vs helm repos + chartmuseum): https://helm.sh/docs/topics/registries/
3. Harbor 2.0 just came out with support for helm3 registry push: https://github.com/goharbor/harbor/releases/tag/v2.0.0

**Comment by stainboy** [comment]
> May the auto-purge will be helpful in your case ? If so , here is a help-wanted issue: #316

Thanks for the information. I believe eventually auto-purge is the key feature to address the issue, especially to save disk space. However, for the time being, the performance issue can be solved easily to improve the cache management mechanism.

**Comment by stainboy** [comment]
> @stainboy thanks for detailed report, few things:
> 
> 1. If you can help with improving caching and performance in chartmuseum via PR, it would be greatly appreciated by many
> 2. Helm 3.0+ has now experimental support for registries, which are a better long term solution for helm charts storage performance (vs helm repos + chartmuseum): https://helm.sh/docs/topics/registries/
> 3. Harbor 2.0 just came out with support for helm3 registry push: https://github.com/goharbor/harbor/releases/tag/v2.0.0

We do plan to create a PR to solve the performance issue. It will be ready in one week or two. Meantime, Harbor 2.0 is also great. I will try out and test the performance a bit. Thanks.
