### ISSUE TITLE
Build is failing, image is quite outdated

### ISSUE THREAD

**Issue by outime** [helm/chartmuseum#347]
The current pipeline in CF has been failing for a while: https://g.codefresh.io/public/accounts/chartmuseum/pipelines/new/helm~2Fchartmuseum~2Fmaster

The latest image available is from 2-3 months ago: https://hub.docker.com/r/chartmuseum/chartmuseum/tags

Is it possible to fix the `Upload test reports` stage? Thanks!

**Comment by jdolitsky** [comment]
@outime thanks for opening, will address as soon as have a chance

**Comment by outime** [comment]
@jdolitsky hey, did you have any chance to take a look?

**Comment by dustinvanbuskirk** [comment]
@jdolitsky Anything I can do to help here?  Looks like DockerHub credentials are no longer valid for the Helm repository there.  Can you take a look at this and let me know if you might be able to fix this for us?

**Comment by jdolitsky** [comment]
Hi there, sorry for delay. Need to fix CI then will do so.

**Comment by jdolitsky** [comment]
Thanks everyone for your patience, builds fixed, latest image updated. Planning to release a v0.13 soon
