### ISSUE TITLE
Missing required flags(s): --storage-local-rootdir

### ISSUE THREAD

**Issue by kicaj29** [helm/chartmuseum#351]
Hi

I just downloaded the newest version of the chartmuseum.
I have such issue:

PS C:\Windows\system32> docker run --rm -it -p 8888:8080 -v C:/helmchartswindows:/charts -e DEBUG=true -e STORAGE=local -e STORAGE_LOCAL_ROOTDIRT=/charts chartmuseum/chartmuseum:latest
**2020-07-05 00:33:20.086819 I | Missing required flags(s): --storage-local-rootdir**

Any ideas why tells that this flag is not set?  It is in the command parameters.
I added folder C:\helmchartswindows to files sharing resources in my docker desktop settings so it should work.

-Jacek

**Comment by jdolitsky** [comment]
@kicaj29 hi, noticing `STORAGE_LOCAL_ROOTDIRT` vs. `STORAGE_LOCAL_ROOTDIR` environment variable. Could you see if that fixes?
