### ISSUE TITLE
Add AWS_SDK_LOAD_CONFIG=1 instructions to s3 instructions on helm hub

### ISSUE THREAD

**Issue by aThorp96** [helm/chartmuseum#355]
The following line from the repository's README should be in [the helm hub docs](https://hub.helm.sh/charts/stable/chartmuseum#using-with-amazon-s3) as well. Would save some headache

`In order to work with AWS service accounts you may need to set AWS_SDK_LOAD_CONFIG=1 in your environment. For more context, please see here.`

**Comment by cbuto** [comment]
This was done in https://github.com/chartmuseum/charts/pull/34
