### ISSUE TITLE
Move the chart for chartmuseum to this repo

### ISSUE THREAD

**Issue by mcfedr** [helm/chartmuseum#356]
Given the 'stable' repo for charts is shutting down and seems to have been removed from hub.helm.sh, the chart for chart museum needs a new home.

If you search for chartmuseum in the hub, several people have already submitted their own copy, https://hub.helm.sh/charts?q=chartmuseum

Source, https://github.com/helm/charts/blob/master/stable/chartmuseum/README.md
Related to, https://github.com/helm/charts/issues/21103

Would the best option be to copy it here, or to another repo? I might be able to do it, but not sure what the best approach is before starting.

**Comment by scbizu** [comment]
We'd better to move the chartmuseum chart into [chartmuseum org](https://github.com/chartmuseum) and mark the one in helm/charts as deprecated? @jdolitsky

**Comment by JoshKCarroll** [comment]
Any movement on this or anyone know what to expect?

I saw https://github.com/chartmuseum/charts exists, would that be the eventual home?

**Comment by jdolitsky** [comment]
I think the chart should probably just live here. If somebody wants to PR it in while maintaining the git history of helm/charts somehow..

**Comment by scottrigby** [comment]
@jdolitsky we have steps written up for this. I pinged you on slack about it - happy to quickly set it up. Have been doing a bunch of these lately.￼

One note about shared vs separate repo: if we want to use the chart releaser GitHub action, sharing a repo with the app would also mean releases for the chart would be mixed with application releases. If that's OK, then no problem (some projects don't mind, others do). If you'd like a cleaner separation there, and still use the automation tools we maintain, we'd want it in a separate git repo.￼￼

I'll just need temporary admin access in whichever git repo you prefer to do some of the settings and automation setup.

**Comment by jdolitsky** [comment]
@scottrigby - just got you admin on chartmuseum/charts

It seems like the chart is released more frequently than the app, so after reading your comment, I think we should actually put it in separate repo

**Comment by tw0517tw** [comment]
Hello, I am wondering how's this going on? It seems chartmeseum/charts has not received commits yet.

**Comment by cvila84** [comment]
Hello, any news on this topic ? I can help if needed !

**Comment by jdolitsky** [comment]
@cvila84 - can you ping me in slack or keybase?

**Comment by itspngu** [comment]
If anyone stumbles into this issue from Google or the stable/chartmuseum readme, the chart mentioned above works fine! Thanks guys.

**Comment by cvila84** [comment]
I think we can close yes @jdolitsky

**Comment by jdolitsky** [comment]
Thank you @cvila84 
Will keep this open while the readme is out-of-date (see https://github.com/helm/chartmuseum/pull/393)
