### ISSUE TITLE
Set "Default" Tenant

### ISSUE THREAD

**Issue by alice-sawatzky** [helm/chartmuseum#361]
It would be cool to be able to set a "default" tenant for multi-tenant setups, so that requests to `/api` or `/index.yaml` would be routed to a catch-all repo. This would especially help with compatibility for users migrating from a single-tenant setup to multi-tenant, since client configs wouldn't have to be updated in sync with the server switchover. At the moment I have this implemented with some nginx rewrite rules, but it could be a handy feature to build in.

**Comment by scbizu** [comment]
We do the migration with dynamic depth mode, which is mentioned in the readme document . More details, we use the `/api` for the default tenant which is set up before the migration and the new tenant will be routed to `/api/new-tenant`.

A little weird , but it works for us .

**Comment by alice-sawatzky** [comment]
whoa cool, didn't realize that was a thing! I didn't realize the docs on the website were incomplete and that the README was the place to go

**Comment by alice-sawatzky** [comment]
is that name "new-tenant" hard-coded? i don't see any mention of a flag to set that name

**Comment by scbizu** [comment]
> is that name "new-tenant" hard-coded? i don't see any mention of a flag to set that name

Just a random name though , you do not need to set the tenant name explicitly . With dynamic depth , you just need to push the chart to the route you want .

[Here](https://github.com/helm/chartmuseum#multitenancy) is the detail operation.

> You may also experiment with the --depth-dynamic flag, which should allow for dynamic depth levels (i.e. all of /api/charts, /api/myrepo/charts, /api/org1/repoa/charts).
