### ISSUE TITLE
Move multi-architecture Docker image to main repo

### ISSUE THREAD

**Issue by zuh0** [helm/chartmuseum#371]
Hello @jdolitsky ,

A couple of months ago, I helped add a GitHub action to build and push a multi-architecture container image to Docker hub.

You wanted to test it by using a staging Docker hub repository `chartmuseumstage/chartmuseum` for a week of so to check everything was fine.

I have been using the arm64 version of this image ever since and it is working fine.

Would you consider pushing these image to your main repository now ?

**Comment by jdolitsky** [comment]
Hi there, sorry for delay. Need to fix CI then will do so.

**Comment by jdolitsky** [comment]
@zuh0 done! thanks for all your work there

**Comment by zuh0** [comment]
My raspberry pi cluster thanks you :) ! 

Glad I could help !
