### ISSUE TITLE
BUG: Helm 3.3.2 errors when trying to add Chartmuseum 0.12.0 repo

### ISSUE THREAD

**Issue by LukeBalizetPatriot** [helm/chartmuseum#374]
We are getting the following error when trying to add a Chartmuseum 0.12.0 repo with the new Helm 3.3.2 version
```
Error: looks like "https://XXXXXXXXXX.com" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: unknown field "serverInfo"
```
I assume it has something to do with [Helm 3.3.2 parsing index.yaml in strict mode](https://github.com/helm/helm/releases/tag/v2.16.11)

**Comment by jdolitsky** [comment]
Hi, this is known issue as of today. A fix is being introduced in Helm, please see https://github.com/helm/helm/pull/8762

**Comment by nerdeveloper** [comment]
Closing this issue, as it appears to be fixed, Feel free to open at any time
