### ISSUE TITLE
Is there a way to limit number of old charts?

### ISSUE THREAD

**Issue by vcorr** [helm/chartmuseum#376]
Is there currently any way to limit number of old charts cumulating over time?

There was some idea to do this back in 2018: https://github.com/helm/chartmuseum/pull/135 but looks like it was never finished.

**Comment by peppe77** [comment]
i was about to ask the very same question :) anyone knows?

**Comment by lkeijser** [comment]
I'm using Minio as a storage backend, and just implemented a simple retention policy in there.

**Comment by s7an-it** [comment]
In GCP bucket as of today I need to do something like keep last 10 for a specific name pattern, as this is not supported I end up running Jenkins based life cycling script.

**Comment by scbizu** [comment]
It is implemented in my PR #466
