### ISSUE TITLE
Migrate release process to follow Helm's

### ISSUE THREAD

**Issue by jdolitsky** [helm/chartmuseum#391]
Should adopt Makefile and release flow, and migrate from:

- Custom S3 bucket to get.helm.sh
- Docker Hub to GitHub registry

Releases should be signed, and should be able to install chartmuseum with install script similar to Helm's

**Comment by jdolitsky** [comment]
Should adopt this document:
https://github.com/helm/helm-www/blob/master/content/en/docs/community/release_checklist.md

**Comment by scbizu** [comment]
Hi @jdolitsky , really busy last month , and I have a short vocation these days . Can we continue with this ? 

Hmm , I read the [deploy.sh](https://github.com/helm/helm/blob/master/.circleci/deploy.sh) from helm , and do not the certain azure namespace or bucket for chartmuseum to store the binary . And also which the store `pattern` can we use ?
