### ISSUE TITLE
BUG: can not delete a chart from repo thoroughly when the chart name is chartname-v1.0-test.tgz

### ISSUE THREAD

**Issue by zhhray** [helm/chartmuseum#398]
When a chart's name like this: chartname-v1.0-test.tgz, you can not delete it from chartmuseum thoroughly.
Check the store path, the file has indeed been deleted. But the cache information still remains in the index-cache.yaml.
So you can search the chart from api /index.yaml, but you can't use it.  You can never delete it.

**Comment by scbizu** [comment]
Thanks for your reporting . The fix #220  is merged into the main and will be released in 0.13.0 .

**Comment by zhhray** [comment]
@scbizu use master code, I still can not delete the chart.
my chart name is `devops-v1.2.0-alpha.2.tgz`. 
Just only delete file from disk, but did not delete from index-cache.yaml

**Comment by scbizu** [comment]
@zhhray How do you start your museum, and which kind of storage do you use ?  Can you try to push a brand new chart to museum and see whether it works ？

**Comment by scbizu** [comment]
And museum has no longer master branch now , if you still build from master ,  you should check whether your upstream is correct XD

**Comment by zhhray** [comment]
> @zhhray How do you start your museum, and which kind of storage do you use ? Can you try to push a brand new chart to museum and see whether it works ？

Sure, I started with Docker Run, but I started with the -v parameter to mount the old charts directory. According to what you said, I deleted it and mounted a new data directory, uploaded the chart and then deleted it. There is no more problem.

**Comment by scbizu** [comment]
> > @zhhray How do you start your museum, and which kind of storage do you use ? Can you try to push a brand new chart to museum and see whether it works ？
> 
> Sure, I started with `docker run`, but I started with the `-v` parameter to mount the old charts directory. According to what you said, I deleted it and mounted a new data directory, uploaded the chart and then deleted it. There is no more problem.

Thanks for your feedback ~
