### ISSUE TITLE
new setup - can't POST anything, see no INFO

### ISSUE THREAD

**Issue by smirnov-mi** [helm/chartmuseum#402]
Hi guys,
I'm trying to setup my chartmuseum, it looks like I' missing something.
Chart itself installed straight forward, I see the welcome to ChartMuseum start page in the browser,
I also see "health"

curl https://charts.my.page/health
{"healthy":true}
but I can't see info and can't POST anything:

curl https://charts.my.page/info
{"error":"not found"}

curl --data-binary "@odoo-1.0.0.tgz" https://charts.my.page/api/charts
{"error":"not found"}

I'm on Rancher 2.5.4, RKE k8s 1.19.4.
this is my yaml I used during the chart installation:

```
---
  env: 
    open: 
      DEBUG: "false"
  ingress:
    enabled: true
    hosts:
      - name: charts.my.page
        path: /
        tls: true
        tlsSecret: charts.my.page-tls
    certManager: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
  persistence: 
    accessMode: "ReadWriteMany"
    enabled: "true"
    size: "2Gi"
    storageClass: "rook-cephfs"
  replicaCount: "1"
```

**Comment by Shamoka** [comment]
I had the same problem.
You need to set `env.open.DISABLE_API=false`

**Comment by smirnov-mi** [comment]
> I had the same problem.
> You need to set `env.open.DISABLE_API=false`

Thanks @Shamoka , 
I just figured it out. Quite a bummer it's not listed in the quick start or "installation instruction".
