### ISSUE TITLE
what is the release date of 0.13.0?

### ISSUE THREAD

**Issue by zhhray** [helm/chartmuseum#404]
FYI

**Comment by scbizu** [comment]
Thanks for opening the issue , the 0.13.0 release still blocks on migrating the bin/image out of s3/DockerHub .

Refers to [0.13.0 mileston](https://github.com/helm/chartmuseum/milestone/2).

But the pre version image should be available with :

```
docker pull ghcr.io/helm/chartmuseum:pre
```

**Comment by zhhray** [comment]
> Thanks for opening the issue , the 0.13.0 release still blocks on migrating the bin/image out of s3/DockerHub and some more loadtesting.
> 
> Refers to [0.13.0 mileston](https://github.com/helm/chartmuseum/milestone/2).
> 
> But the pre version image should be available with :
> 
> ```
> docker pull ghcr.io/helm/chartmuseum:pre
> ```

OK, Thanks for reply.

**Comment by jdolitsky** [comment]
just released!
