### ISSUE TITLE
The latest version (v.0.13.0) is not available in Docker Hub.

### ISSUE THREAD

**Issue by tardis4500** [helm/chartmuseum#416]
The latest version (v.0.13.0) is not available in Docker Hub.

**Comment by scbizu** [comment]
Hi , @tardis4500 we migrate to the GitHub Registry for some reasons. And it should be available in the [official Helm Registry](https://github.com/orgs/helm/packages/container/package/chartmuseum) 

via Docker pull:

```
docker pull ghcr.io/helm/chartmuseum:canary
```

See #416 for details .

Thanks.
