### ISSUE TITLE
How to upload meta file artifacthub-repo.yml?

### ISSUE THREAD

**Issue by acim** [helm/chartmuseum#419]
This is required by ArtifactHub to verify ownership and should be visible at the similar URL as index.yaml, but I see no way how to add it to chartmuseum.

**Comment by scbizu** [comment]
AFAIK we do not registered in ArtifactHub yet . And It seems that ArtifactHub need the metadata file to claim the ownership ?

**Comment by acim** [comment]
Well, thisi optional, but if you want to get badge "Verified publisher", you need to have this file and repoID from the ArtifcacttHub inside. I solved this at the moment by nginx ingress rewrite rule, but it would be nice if you support it.

**Comment by scbizu** [comment]
Thanks for your advice .

/cc @jdolitsky

**Comment by jdolitsky** [comment]
Seems like we can start with a flag like `--artifact-hub-repo-id=xxxxx`, and just populate the `repositoryID` field here: https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml#L12

@acim - do you have any need for the `owners` / `ignore` fields?

**Comment by acim** [comment]
At this moment this would be enough. Thank you.
