### ISSUE TITLE
Multi-tenant server is broken with local storage in v0.13.0

### ISSUE THREAD

**Issue by maybe-sybr** [helm/chartmuseum#421]
It looks like a change in `cache.go` to get the actual chart objects from storage when fetching the chart list forgot to join the repository path prefix to the object path like it should. The offending commit is ff22877341 and the lines in question are below:

https://github.com/helm/chartmuseum/blob/ff22877341b42b91efd3a4d1e5fcbab9a6eb7d91/pkg/chartmuseum/server/multitenant/cache.go#L204-L213

L207 should be doing `pathutil.Join(repo, object.Path)` like similar calls elsewhere in this and other files:

https://github.com/helm/chartmuseum/blob/ff22877341b42b91efd3a4d1e5fcbab9a6eb7d91/pkg/chartmuseum/server/multitenant/cache.go#L312-L317

I'd guess that this works fine with other storage providers and since they only seem to remove a prefix if it is present, they would have handled the missing prefix happily. But I'm commenting based on a short period of reading this code so it's definitely something worth looking into and smoke testing against more storage backends at least.

**Comment by maybe-sybr** [comment]
A horrible workaround for anyone wanting to using multi-tenancy and the local backend before this gets fixed if to do:
```
$ find /path/to/charts -type f -name '*./tgz' -exec ln -sr '{}' /path/to/charts/ ';'
```

That'll create a symlink in the storage root to each chart file in its actual repository dir and keep the broken cache list code happy.

**Comment by scbizu** [comment]
Thanks for your bug report , I will take a look at this .

**Comment by scbizu** [comment]
## Reproduce Steps

* bootstrap chartmuseum with depth>0 (multi-tenants)
* **remove cache index file**
* `GET` /api/org/repo and chartmuseum responses with the not found error

## Details

The previous commit https://github.com/helm/chartmuseum/commit/ff22877341b42b91efd3a4d1e5fcbab9a6eb7d91 raises a bug that the path is incorrect in multi-tenant , multi-tenant chart path should be `prefix/path` than `path` in single tenant .  And the tests also do not cover with the multi-tenant server(the single tenant sees ok for now).

I will self-assign this issue and provide a fix maybe in v0.13.1 release .

**Comment by maybe-sybr** [comment]
Thanks @scbizu - it looks like that PR will fix the issue nicely. Let me know if there is anything I can do to help validate the change

**Comment by scbizu** [comment]
We still need the tests to cover the multi-tenant server and please wait the PR is able to merge .
