### ISSUE TITLE
Redis usage question

### ISSUE THREAD

**Issue by outime** [helm/chartmuseum#425]
I'm using ChartMuseum with the following env vars (among others):

```
CACHE: redis
CACHE_REDIS_ADDR: localhost:6379
CACHE_REDIS_PASSWORD: ""
CACHE_REDIS_DB: "0"
```

Redis runs as a sidecar. The container is accessible and ChartMuseum doesn't seem to complain. However if I access through redis-cli and try to list the available keys it doesn't show anything. I'd have expected to at least find some key related to the `index.yaml`.

What'd Redis be used for? Is what I experienced normal?

**Comment by jdolitsky** [comment]
It should be saving the index.yaml. Here is the code: https://github.com/helm/chartmuseum/blob/ff22877341b42b91efd3a4d1e5fcbab9a6eb7d91/pkg/chartmuseum/server/multitenant/cache.go#L382

Are you seeing any `Entry found in cache store` in the logs if you turn on debug?

**Comment by outime** [comment]
@jdolitsky I found out why after verifying that your comment made sense: my client wasn't listing empty named Redis keys. I just used an up-to-date `redis-cli` and I could see it. Another topic for discussion would be why an empty name but that's a very minor problem now :) thanks!
