### ISSUE TITLE
chartmuseum.com appears to be down..

### ISSUE THREAD

**Issue by gillesde** [helm/chartmuseum#426]
The website associated with the project [ChartMuseum](https://chartmuseum.com) is currently down and its certificates is shown as invalid, as illustrated in the screenshot below. 

![image](https://user-images.githubusercontent.com/68287234/110123622-07e80500-7db9-11eb-8ad8-1177c26ddaf2.png)

**Comment by jdolitsky** [comment]
related: https://github.com/helm/helm-www/issues/1015

**Comment by jdolitsky** [comment]
resolved!
