### ISSUE TITLE
Permissions Error uploading chart

### ISSUE THREAD

**Issue by kronik22** [helm/chartmuseum#437]
I am getting a permissions error when trying to upload my first chart.

curl --data-binary "@chartmuseum-2.16.0.tgz" https://chartmuseum.mycompany.com/api/charts
{"error":"mkdir /\": permission denied"}

I am using the dockerhub.com chartmuseum:v0.12.0 release with an NFS persistent volume that is attached at the path /storage. The website documentation for local storage could use more documentation. If i don't attach a pc/pvc where would the ./chartmuseum file path be created on the first upload? How can i validate that the permissions are set properly for the local storage path so that the chartmuseum binary can write to the desired path? Adding a permissions check on the storage backend to the binary's global options would help with troubleshooting.

**(From Chartmuseum.com website)**
USING WITH LOCAL FILESYSTEM STORAGE
Make sure you have read-write access to ./chartstorage (will create if doesn’t exist on first upload)

chartmuseum --debug --port=8080 \
  --storage="local" \
  --storage-local-rootdir="./chartstorage"

The website is current offline for viewing by a secure browser session. There appears to be a certificate issue with the site.

**Comment by scbizu** [comment]
Can u paste some chartmuseum logs ? It seems like the rootdir flag not work or something wrong with your dir permissions, and what is your NFS mount path ? 

And the chartmuseum site is currently down and will do some migration , you can read examples from our [readme](https://github.com/helm/chartmuseum/blob/main/README.md) , thanks for reporting anyway .

**Comment by kronik22** [comment]
I was able to resolve the issue. The documentation and the charts need additional clarification. The documentation uses quotes:
**--storage-local-rootdir="./chartstorage"**
while the chart does not quote the value:
{{- if eq .Values.env.open.STORAGE "local" }}
        **- --storage-local-rootdir={{ .Values.persistence.path }}**
{{- end }}

If the --storage-local-rootdir value is quoted it fails to add the storage when processing the option
