### ISSUE TITLE
panic then storage is tencent cos in 0.13.1 

### ISSUE THREAD

**Issue by pavlelee** [helm/chartmuseum#445]
![image](https://user-images.githubusercontent.com/5382358/113847419-0c457a80-97ca-11eb-883e-5f69e960e88c.png)
ChartMuseum version v0.13.1 (build 79bb39c)

Look like vendor version not update, because tencent cos sdk is ok.

https://github.com/tencentyun/cos-go-sdk-v5/blob/v0.7.21/object.go#L189

**Comment by pavlelee** [comment]
https://github.com/tencentyun/cos-go-sdk-v5/pull/119
will fix it

**Comment by scbizu** [comment]
Thank you for your reminds , we will upgrade the dependency in the next available version .

**Comment by pavlelee** [comment]
@scbizu Already fix in https://github.com/tencentyun/cos-go-sdk-v5/blob/v0.7.23/object.go，close pr

**Comment by LeoQuote** [comment]
I'm using chartmuseum 0.13.1 but the error persists, is this fix released?
