### ISSUE TITLE
Docs site reports wrong helm chart repo

### ISSUE THREAD

**Issue by williambrode** [helm/chartmuseum#451]
Wasn't sure where to report but the docs site: https://chartmuseum.com/docs/#helm-chart

Reports the old helm chart repo instead of the new one reported in the readme on this repo: https://github.com/chartmuseum/charts/tree/main/src/chartmuseum

**Comment by scbizu** [comment]
#356 address some context about the migration but the doc haven't change yet , maybe you can open an issue [there](https://github.com/chartmuseum/www) and close the issue here?

**Comment by scbizu** [comment]
It will be fixed in https://github.com/chartmuseum/www/pull/11 , thank you ~
