### ISSUE TITLE
Chart info is still in cache after deleting

### ISSUE THREAD

**Issue by jiarongxu1** [helm/chartmuseum#455]
Hi experts,
I have encountered a problem when using chartmuseum 0.12.0.
After deleting one chart, and then using the chartmuseum api to get all the charts, the deleted charts is still there, and the index-cache.yaml also not updated.

And after some tests, I found this issue maybe related with the chart name and version.
When the chart name is "xxxx-3.0.0-12" the "xxxx" is the name, while the "3.0.0-12" is the version, the issue will happen.
And when the chart name is "xxxx-3.0.0+12" , while the version is "3.0.0+12", then everything works fine.

So the problem maybe related with the chart version contains dash "-" .

And I enabled the debug log, seems it really parsed the version incorrectly after delete the chart, the debug message like
"Removing chart from index","repo":"mychart","name":"xxxx-3.0.0","version":"12","reqID":"c701e2976e1aa7fc1a395728090801ea"

Could you guys help to confirm that whether it is a chartmuseum issue or not?

Thanks and regards

**Comment by peppe77** [comment]
@jiarongxu1 we have had problems with v0.13.1 [https://github.com/helm/chartmuseum/issues/453] similar to what you are herein reporting. We are not sure if it is related to chart version though. The problem we reported has been causing a lot of problems specially on our nightly builds (it is intermittent though when it happens chart is successfully pushed upstream via API and we can see chart in S3 though it is not in the index). We are now on the process to roll back to v0.8.2 (one we used to have) that does not have this problem though has known perf issue on helm repos with big number of charts (w/as keep helm repos clean). cheers

**Comment by scbizu** [comment]
@jiarongxu1  we have the fix in #220 and released in v0.13.0 and a fix in v0.13.1 , you can bump up your version to 0.13.1 and to see if your problem is fixed .

**Comment by scbizu** [comment]
@peppe77 I can not reproduce it on my local storage , can you try to use the local storage for some testing ?

**Comment by jiarongxu1** [comment]
> @jiarongxu1 we have the fix in #220 and released in v0.13.0 and a fix in v0.13.1 , you can bump up your version to 0.13.1 and to see if your problem is fixed .

Ok, thanks, I will try to test 0.13.1

**Comment by scbizu** [comment]
I'll close it for now . Feel free to reopen it .

**Comment by HamzaMalik95** [comment]
Hi Guys,
I am facing a similar issue and my ChartMusuem is on latest verion

NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
chartmuseumv1   chartmuseum-ns  1               2022-06-22 17:56:03.0983315 +0500 PKT   deployed        chartmuseum-3.8.0       0.14.0     

But I am facing this issue,
