### ISSUE TITLE
Fix CI, auto-publish to GHCR, sign container+artifacts with Sigstore

### ISSUE THREAD

**Issue by jdolitsky** [helm/chartmuseum#481]
Should be able to use `GITHUB_TOKEN` to publish to GHCR (vs secrets)

Edit: also, find missing gopher images in README?

**Comment by scbizu** [comment]
maybe #419 is related ?

**Comment by jdolitsky** [comment]
I think 419 requires code changes, to expose some file required by artifacthub

**Comment by scbizu** [comment]
OK , I will self-assign this .
