### ISSUE TITLE
Missing repo metrics from 3.1.0

### ISSUE THREAD

**Issue by nathan9120** [helm/chartmuseum#487]
Having exposed the metrics to prometheus i can see all metrics except for the 2 below:

chartmuseum_charts_served_total | Gauge | {repo="*"} | Total number of charts
-- | -- | -- | --
chartmuseum_charts_versions_served_total | Gauge | {repo="*"} | Total number of chart versions available

These are the metrics that i can see when querying the metrics endpoint

![Screenshot 2021-09-15 at 09 55 43](https://user-images.githubusercontent.com/17130088/133403201-dbf846ce-788d-499d-85f1-0fa8a1ba2a2c.png)

is there something that i need to enable to obtain these additional metrics?

Current config: 

```
  open:
    ...
    STORAGE: amazon
    STORAGE_AMAZON_BUCKET: ${bucket}
    STORAGE_AMAZON_PREFIX: charts
    STORAGE_AMAZON_REGION: eu-west-2
    AWS_SDK_LOAD_CONFIG: "1"
    DEPTH: 1
    DISABLE_METRICS: false
    DISABLE_API: false
    DISABLE_STATEFILES: false
    DEBUG: true
    AUTH_ANONYMOUS_GET: true
```

**Comment by scbizu** [comment]
HI @nathan9120  , I can find these two metrics in the latest cm version , and can you provide the correct version or bump to the latest cm version ? 

But , maybe there is a typo in our readme , the  `chartmuseum_charts_versions_served_total` should be `chartmuseum_chart_versions_served_total`.
