### ISSUE TITLE
Support helm 3.7 `push`

### ISSUE THREAD

**Issue by Ashtonian** [helm/chartmuseum#490]
Helm push doesn't seem to be working with chartmueseum. 

```sh
helm repo add myrepo https://charts.example.com/ --username *** --password ***
helm push mychart.tgz oci://charts.example.com             
```

**Comment by scbizu** [comment]
Please provide some more details ? For example , what is your cm version , do you use the [helm-push plugin](https://github.com/chartmuseum/helm-push) or the Helm OCI push ?

**Comment by Ashtonian** [comment]
Helm push plugin doesn't work with latest helm because it conflicts with the new `helm push` command. The helm push plugin defaults to and I think only allows oci:// currently. CM is latest v0.13.1 via helm chart install.

**Comment by scbizu** [comment]
ok , I know , but sorry , CM is not compatible with the new helm push (via `OCI` way) , you should host your own [OCI based Helm Repository](https://helm.sh/docs/topics/registries/)

**Comment by sagikazarmark** [comment]
So, I'm not sure if the new push command is OCI only. Quoting from helm/helm#9782:

> This adds a new `helm push` subcommand and `Pusher` interface for uploading charts, which can be expanded to other non-OCI protocols and various uploader plugins in the future (equivalent of `helm pull` subcommand and `Getter` interface).

This tells me that plugins can now implement a push interface, so this probably an issue for the helm-push plugin: chartmuseum/helm-push#103

Not sure what the original intent of this issue was though.

**Comment by scbizu** [comment]
@sagikazarmark Per my understanding , the issue should be kept in `helm-push` and nothing about  CM itself , I am going to  close this issue .

/cc @Ashtonian
