### ISSUE TITLE
Add Get Deployment Names In Namespace

### ISSUE THREAD

**Issue by sjakubek** [helm/chartmuseum#495]

**Comment by scbizu** [comment]
What do you mean ?

**Comment by sjakubek** [comment]
Hello,

I meant the same keyword as implemented for pods, i.e. Get Pod Names In Namespace - or one that simply returns a list of strings that corresponds to the list of deployment names that match the defined name_pattern. This would allow an easy way to iterate over deployment names in order to, for example, run a Delete keyword.
