### ISSUE TITLE
Where is the Helm Chart for Chartmuseum

### ISSUE THREAD

**Issue by kferrone** [helm/chartmuseum#497]
Where did the helm chart for this project go? 
The only one is still in the old stable repo which says it is deprecated.
Is this still the only way to install it?

**Comment by scbizu** [comment]
We host the latest chart [here](https://github.com/chartmuseum/charts/tree/main/src/chartmuseum) .

And it is mentioned in [README](https://github.com/chartmuseum/charts/tree/main/src/chartmuseum).
