### ISSUE TITLE
index-cache.yaml fails to be stored on Azure Blob storage if its size is more than 4MB

### ISSUE THREAD

**Issue by slienard** [helm/chartmuseum#500]
Hello,

   when using Azure blob storage as backend, if the size of the "index-cache.yaml" file is more than 4MB, it fails to be saved and ends up with a size of 0 byte (empty).

When it happens, the log contains the following message:

`{"L":"WARN","T":"2021-11-09T09:48:11.593Z","M":"[2166] Error saving index-cache.yaml","repo":"XXXX","error":"storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.\nRequestId:XXXXXXXXXXXXXXX\nTime:2021-11-09T09:48:11.5767992Z, RequestInitiated=Tue, 09 Nov 2021 09:48:10 GMT, RequestId=XXXXXXXXXXXXXX, API Version=2018-03-28, QueryParameterName=, QueryParameterValue=","reqID":"XXXXXXXXXXXXXXXXXXXXX"}`

But the repositories continues to be accessible and up to date since the in-memory version of the file is OK.

Big problems happen if the ChartMuseum service is restarted, then, the in-memory version is lost and in our case, the generation of the file fails because, with many charts, it takes too much time, leaving the repository unusable.

This Azure blob storage limit is described here: https://docs.microsoft.com/en-us/troubleshoot/azure/general/request-body-large

Regards.

**Comment by scbizu** [comment]
Thans fot reporting ,  I am not Azure Users though , but I found maybe [this issue(and the linked PR)](https://github.com/Azure/azure-sdk-for-go/issues/562) fixes this problem ?  If though , it's time for us to bumping up the Azure Storage  dependency in  chartmuseum/storage .

**Comment by scbizu** [comment]
It should be fixed in the v0.14.0 , see latest cm storage version https://github.com/helm/chartmuseum/pull/540 .
