### ISSUE TITLE
Authorization fails

### ISSUE THREAD

**Issue by Olesp** [helm/chartmuseum#502]
Hi,
I have deployed this app using a helmchart.
It is running pretty good except for one thing and I cannot figure out why.
I'm using Basic auth to secure api urls.
However, when I try to `helm repo add mychartmuseum https://my.chartmuseum.com/ --username <myusername> --password <mypassword>` it doesn't work and return`{"error":"unauthorized"}`.
I'm sure the password is correct because I can omit the --password flag and enter the password when I'm prompted and it will work. 
Same thing when  I `curl https://my.chartmuseum.com/ --user <myusername:mypassword>` but when i ommit the password and only enter it when prompted it works.
Apart from this everything seems to work even pushing a chart when logged in.

I cannot figure why this is not working.
Chartmuseum version: 0.13.1
Helm version:  3.7.1

As for the configuration I use the env vars:

- env.existingSecretMappings.BASIC_AUTH_USER
- env.existingSecretMappings.BASIC_AUTH_PASS
- env.existingSecret
- env.open.DISABLE_API

Let me know what infos you could need.

**Comment by cbuto** [comment]
@Olesp have you been able to consistently reproduce this issue? I wonder if is possible that the password being used on the command line was being escaped due to special characters? 

I think a good start would be any logs you have when this was happening, thanks!
