### ISSUE TITLE
Azure Arc/Kubernetes question

### ISSUE THREAD

**Issue by sivakolisetti** [helm/chartmuseum#505]
When running the following, I get the error shown.  Thing is, I already have Helm installed and functional.
1)	Is there a way to prevent the helm install?
2)	If not, how do I surmount the CERTIFICATE_VERIFY_FAILED error?

(Running latest AZ CLI in Ubuntu 20.04 LTYS via WSLv2 on my Win10 system)

az connectedk8s connect --name nvlastanzu-arc --resource-group RG-AzureArcTest --location westus2
This operation might take a while...

Downloading helm client for first time. This can take few minutes...
Failed to download helm client.
Please check your internet connection.<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

I have internet connection but still getting error with cert failed

**Comment by scbizu** [comment]
Seems like a helm issue , nothing about the chartmuseum ?

**Comment by cbuto** [comment]
👋 @sivakolisetti As @scbizu pointed out, this looks like an issue with the Azure CLI (not related to ChartMuseum). If this is still an issue, I’d recommend reaching out to Azure support!
