### ISSUE TITLE
[Question]Why chartmuseum doesn't support previewing the values yaml of a chart?

### ISSUE THREAD

**Issue by xiechengsheng** [helm/chartmuseum#509]
Hi there, Since chartmuseum can provide the interface `GET /api/charts/<name>/<version>` which describes a chart version, how about providing an interface `GET /api/charts/<name>/<version>/value` which shows the `values.yaml` in chart version? Because the `values.yaml` is important for developers to generate the helm applications in many CD systems.

So why we don't implement this interface until now? Any help will be appreciated!

**Comment by scbizu** [comment]
Good point , it will make sense to me , would you like to contribute on this feature ?

**Comment by xiechengsheng** [comment]
Sure. Will start this ASAP.

**Comment by cbuto** [comment]
Closed by https://github.com/helm/chartmuseum/pull/551.
