### ISSUE TITLE
securityContext: fsGroup  insufficient permissions

### ISSUE THREAD

**Issue by volker-raschek** [helm/chartmuseum#524]
Hello, 
I have deployed chartmuseum in my cluster. However I get upload error when `fsGroup` does not equal `1000`. 

The goal is to make sure that the nfs share does not belong to group `1000` to avoid that local users get access to this directory. Therefore I would like to set the permission to `root:20000`. 

The GID can be changed with  `fsGroup`, but the directories are created by chartmuseum with `0755`. Thus chartmuseum is not able to save charts into a repository.

**Comment by cbuto** [comment]
hi @volker-raschek 👋 , just to understand the use case, you would want the directories created by chartmuseum to allow reading/writing for `fsGroup` GID you set? I think that sounds reasonable to me.
