### ISSUE TITLE
How to customize welcome page

### ISSUE THREAD

**Issue by Pezhvak** [helm/chartmuseum#550]
I was wondering if it's possible to change contents of the welcome page, i want to add some instructions to the page so users can follow them in order to install charts.

**Comment by scbizu** [comment]
Sorry , this is not support yet . Or you can raise a pr to support this .

**Comment by dirien** [comment]
Hi @Pezhvak and @scbizu,

i made a PR to support custom welcome page -> #557

looking for your feedback.
