### ISSUE TITLE
Can't Pull latest image from GitHub Container Registry 

### ISSUE THREAD

**Issue by ahasna** [helm/chartmuseum#572]
# Problem

when attempting to pull latest image I get the following:

```bash
$ docker pull ghcr.io/helm/chartmuseum:sha256-d926176c85d52f6274a90b49ed0ee8341e6f7d1a57b10c42d3c0a2db45d3255e.sbom

	  sha256-d926176c85d52f6274a90b49ed0ee8341e6f7d1a57b10c42d3c0a2db45d3255e.sbom: Pulling from helm/chartmuseum
	  d59f9dd5893d: Extracting [==================================================>]  1.016MB/1.016MB
	  failed to register layer: Error processing tar file(exit status 1): archive/tar: invalid tar header
```

# Workaround

using a different tag solved the problem

```bash
$ docker pull ghcr.io/helm/chartmuseum:v0.14.0

	v0.14.0: Pulling from helm/chartmuseum
	9b3977197b4f: Pull complete
	8abc8a54854f: Pull complete
	1bd152fd82d3: Pull complete
	Digest: sha256:878ef6a31fa08228ac4e1beff07060bd800f1a4b6ce71c45bb560d6aeec79b8a
	Status: Downloaded newer image for ghcr.io/helm/chartmuseum:v0.14.0
	ghcr.io/helm/chartmuseum:v0.14.0
```

**Comment by cbuto** [comment]
Thanks for reporting this @ahasna!

It looks like our latest build failed silently when pushing the image… I’m not sure why though. We’ll look into it and get it fixed up. 

I.e https://github.com/helm/chartmuseum/runs/5739123679?check_suite_focus=true#step:13:296

**Comment by cbuto** [comment]
Actually it looks like the failure was retried and succeeded. The command you used was attempting to pull the `sbom` and not the actual image. 

This is the command you should use for pulling the latest image:
```
ghcr.io/helm/chartmuseum:canary@sha256:d926176c85d52f6274a90b49ed0ee8341e6f7d1a57b10c42d3c0a2db45d3255e
```

**Comment by ahasna** [comment]
Sounds good! 

I reported this because I used what is in the documentation for pulling what I ch resulted in an error... Once I used the version as tag all worked so I thought I should report it so you guys can either fix it or give me some guidance.

Thank you very much 👍

**Comment by ahasna** [comment]
I think the documentation should better state how to pull latest 😅

It is still using the `sbom` in the thag
![Screenshot_20220405-043233_Chrome](https://user-images.githubusercontent.com/25301467/161667776-e1bf65d8-257d-4a4a-ae7d-17e8835d749f.jpg)
