### ISSUE TITLE
Ingress ServiceBackendPort: "use-annotation" got "string", expected "integer"

### ISSUE THREAD

**Issue by cpboyd** [helm/chartmuseum#581]
From https://artifacthub.io/packages/helm/chartmuseum/chartmuseum#extra-paths:

```sh
helm install my-chartmuseum chartmuseum/chartmuseum \
  --set ingress.enabled=true \
  --set ingress.hosts[0].name=chartmuseum.domain.com \
  --set ingress.extraPaths[0].service=ssl-redirect \
  --set ingress.extraPaths[0].port=use-annotation \
```

This, however, results in the following error:

> Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend.service.port.number): invalid type for io.k8s.api.networking.v1.ServiceBackendPort.number: got "string", expected "integer"

Replacing `use-annotation` with an integer works, but it'd be nice to simply refer to port defined in the policy.

**Comment by cbuto** [comment]
@cpboyd thanks for creating the issue! I'm going to recreate this in the https://github.com/chartmuseum/charts and we can continue the convo there.
