### ISSUE TITLE
How can I "helm install" using restAPI or curl?

### ISSUE THREAD

**Issue by juan0125** [helm/chartmuseum#586]
I want to helm chart install using restAPI or curl.
But It doesn't seem to work.
Is there any way to helm install?
Could you help me for this?

![image](https://user-images.githubusercontent.com/84367359/169935403-179cc04e-0e68-4e2e-8964-fa23c63feaaf.png)

![image](https://user-images.githubusercontent.com/84367359/169935253-6566d870-ccc3-4be8-ab75-d558dc1a7350.png)

**Comment by cbuto** [comment]
👋 @juan0125 I'm not sure I fully understand. Are you asking how to `helm install` a chart served by ChartMuseum? The process is described here https://chartmuseum.com/docs/#installing-chartsinto-kubernetes. 

Can you describe your goal? and the steps you've already taken?

**Comment by juan0125** [comment]
@cbuto Thank you for your interest.
My goal is **"helm install chartmuseum/mychart"** using **restAPI ( GET /charts/mychart-0.1.0.tgz )** described in https://chartmuseum.com/docs/#installing-chartsinto-kubernetes.

My condition is as below.
- Chartmuseum : http://10.178.71.18:30080
- mychart           : mysql-8.9.6.tgz ( This chart is already uploaded )

I sent the command http//10.178.71.18:30080/mysql-8.9.6.tgz using restAPI,
but there is unknown response and helm chart is not installed.

Could you help me?

**Comment by cbuto** [comment]
Ah okay I think I understand, so the API will not install the chart. The route `/charts/mychart-0.1.0.tgz` returns the chart file which can then be installed via the `helm` CLI (or some other tool). ChartMuseum simply hosts Helm charts, the installation and management of charts in Kubernetes is handle by other tools.

Does that help clear things up?

**Comment by juan0125** [comment]
I understand your answer.
Thank you for your help.
I need to find another way.
