### ISSUE TITLE
Steps for graceful termination of chart museum application

### ISSUE THREAD

**Issue by swapsingh** [helm/chartmuseum#617]
steps to test the Graceful termination of Chart museum and Pod delete scenario. 
Is there any documentation for this.
what are the risks on shutdown of chart museum.

**Comment by cbuto** [comment]
@swapsingh Is there a specific problem you experienced? I don't think there are any known limitations with shutting down ChartMuseum

**Comment by swapsingh** [comment]
How to get the exit code after deleting the pod?

**Comment by swapsingh** [comment]
The Task is completed
