### ISSUE TITLE
No License for package github.com/NetEase-Object-Storage/nos-golang-sdk 

### ISSUE THREAD

**Issue by Kiran-38** [helm/chartmuseum#646]
Hi Team,
         I see there is a go package(github.com/NetEase-Object-Storage/nos-golang-sdk v0.0.0-20191125093154-335c2b73bf6b)
 which chart-museum is using.
And this package is not defining any license, is it really okay to use the unlicensed package in chartmuseum?
 As far as I know this kind of package is propriety of it's creator.

**Comment by Kiran-38** [comment]
@davidkarlsen @spiffxp @mattfarina @outime Can anyone please respond on this issue raised ?

**Comment by jmk75** [comment]
This is a serious issue as this practically means that ChartMuseum cannot be used in any products as it uses proprietary, non-oss library (non-licensed github.com/NetEase-Object-Storage/nos-golang-sdk library)

**Comment by cbuto** [comment]
Thanks for bring this up @Kiran-38. It looks like that package is used by the `chartmuseum/storage` package to implement the NetEase object storage provider (https://github.com/chartmuseum/storage/blob/main/netease.go). 

@jdolitsky what do you think the best approach is here? It doesn't look like there's any real alternatives to that package (i'm also not super sure what NetEase is and if we want to continue supporting it)

**Comment by scbizu** [comment]
> i'm also not super sure what NetEase is

Since I am a Chinese developer , maybe I am familiar with the NetEase Object Storage , the official site is [here](https://sf.163.com/product/nos), the main-user maybe the Chinese Mainland .gov users , I will try to contact them , it's better that we can raise a pr deprecation PR in storage though .

**Comment by Kiran-38** [comment]
@jdolitsky Can you please comment on what @cbuto has posted please. I see this is a risk for the chartmuseum user of using the unlicensed code. I request you to solve as early as possbile. Thank you

**Comment by jdolitsky** [comment]
I think we should just drop the support for netease entirely, at least for now. People have asked for license since 2020 with no response: https://github.com/NetEase-Object-Storage/nos-golang-sdk/issues/4

**Comment by jdolitsky** [comment]
We've also been using a fork for a while too. See https://github.com/NetEase-Object-Storage/nos-golang-sdk/pull/2

**Comment by scbizu** [comment]
> I think we should just drop the support for netease entirely,

I agree with this , I contact some developers in Netease but has no response for now . If we all agree with this , I can raise the PR to deprecate the NOS dependency.

**Comment by Kiran-38** [comment]
Hi @jdolitsky if the PR is raised to deprecate is there any time frame it is planned to fix, like next version release like v0.16.0?
If yes, when can we expect the next release please. It would be great to know. Thanks

**Comment by cbuto** [comment]
@scbizu I'm good with removing support for NOS!

**Comment by jdolitsky** [comment]
looks like maintainers are all in agreement, we just need somebody to make the changes.

@Kiran-38 - if you or somebody on your team could assist here, we will take care of merging PRs and cutting releases. It would require first a change in chartmuseum/storage, then afterwords in chartmuseum itself

**Comment by scbizu** [comment]
I maybe can self-assign this . @jdolitsky

**Comment by jdolitsky** [comment]
chartmuseum/storage v0.13.0 released with NOS removed, thank you very much @scbizu

**Comment by Kiran-38** [comment]
Thnak you @jdolitsky for the resolution. When can we get the updated changes for dropping support of NOS in the helm/chartmusuem github.
Also was occupied with some other work, but if there is any other work that I can contribute. Happy to help.

**Comment by jdolitsky** [comment]
whats left is to update helm/chartmuseum go modules to include chartmuseum/storage v0.13.0, and drop all mention of NOS in the code and readmes etc

**Comment by cbuto** [comment]
I put up https://github.com/helm/chartmuseum/pull/656 to remove references to netease. The last thing would be to remove references in the docs site.
