### ISSUE TITLE
K8S version compatibility info is missing

### ISSUE THREAD

**Issue by Kiran-38** [helm/chartmuseum#652]
Hi @cbuto, Need one info about there is any next latest ChartMuseum version releasing with the security and package fixes, if yes what is the K8S version supported in that? 

If its not available yet, is there a way to check current new version available is compatible with K82 1.25?

Thanks
kiran M

**Comment by scbizu** [comment]
Do you mean our Helm charts ? I assume that it depends on helm , if the latest `helm install` can install our charts , then we are compatible with the new k8s version .
