### ISSUE TITLE
'helm push' mentioned in docs does not work

### ISSUE THREAD

**Issue by kmathewmk** [helm/chartmuseum#653]
https://chartmuseum.com/docs/
shows
![image](https://user-images.githubusercontent.com/52198810/210759146-2a445c56-3125-43b5-9792-d7b5dd6685fe.png)
but this does not work.

Looking at README.md "helm push" has been replaced with "helm cm-push"
https://github.com/helm/chartmuseum/commit/4412d393466f138bc68c4d65e77f431cc70d2246#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
and this works

Could the website be updated to reflect this correction?

**Comment by scbizu** [comment]
@kmathewmk  Thank you , it should be fixed now .
