### ISSUE TITLE
Recommended way to run chartmuseum in Kubernetes

### ISSUE THREAD

**Issue by pgier** [helm/chartmuseum#707]
Is there a helm chart or some other example of how to run chartmuseum itself in Kubernetes?
I found this Chart https://github.com/helm/charts/tree/master/stable/chartmuseum but it seems to be deprecated and no longer maintained.  Would it be useful to update that chart and migrate it to this repository?

**Comment by pgier** [comment]
I found this project https://github.com/chartmuseum/charts
I guess this is the current Helm chart for chartmuseum?

**Comment by scbizu** [comment]
> I found this project https://github.com/chartmuseum/charts

Yes
