### ISSUE TITLE
Compatibility of chartmuseum with Kubernetes

### ISSUE THREAD

**Issue by vishnudasp28** [helm/chartmuseum#736]
Hello Team
 
I would like to know if the current version of chartmuseum v0.16.0 is compatible with Kubernetes 1.27. @jdolitsky Can you please provide the information about it.
 
@scbizu May I know when will be the next chart-museum version released. @cbuto  What will be the tentative date of next chartmuseum version release?

**Comment by scbizu** [comment]
Soon , see #737
