### ISSUE TITLE
Can browse to default index.html, but "helm repo add" returns 404

### ISSUE THREAD

**Issue by sierrasoleil** [helm/chartmuseum#763]
I installed Chartmuseum in EKS via the helm chart. Everything _appears_ to be working; no errors from the S3 connection, and I can browse to the default "Welcome to ChartMuseum!" page. However, `helm repo add <repo-name> <repo-url>` always fails with:
`Error: looks like "https://<repo-url>/" is not a valid chart repository or cannot be reached: failed to fetch https://<repo-url>/index.yaml : 404 Not Found`

I can't find any issues with the ALB, Ingress or Service. I enabled debug logging, but the only entries in the pod logs are the health checks.

**Comment by wmcnamee-coreweave** [comment]
I just tried running this locally, and I'm also getting a 404 for `http://localhost:8080/index.yaml`
