### ISSUE TITLE
TLS Client Cert Authentication

### ISSUE THREAD

**Issue by jgiles** [helm/chartmuseum#79]
This is related to the excellent proposal in https://github.com/kubernetes-helm/chartmuseum/issues/59, but should be solvable immediately rather than as a long-term effort.

The Helm client supports TLS client certificate authentication:
https://github.com/kubernetes/helm/issues/1038#issuecomment-297043419

It would be great if chartmuseum supported a `--tls-ca-cert` which would perform client certificate authentication of incoming requests, accepting client certs issued by the trusted CA.

Perhaps this is already supported, but I can't find it in the documentation.

**Comment by jdolitsky** [comment]
@jgiles hi thanks for opening, sorry for delay. will look into asap.

**Comment by amerghazal** [comment]
I'll be happy to pick this up, thank you

**Comment by jdolitsky** [comment]
@jgiles @Smana this is finally supported in latest/master thanks to @amerghazal #203! Closing
