### ISSUE TITLE
Should support different auth for api and server

### ISSUE THREAD

**Issue by goruha** [helm/chartmuseum#90]
Use case

1. There is private charts repo backed by chartmuseum.
2. There is ci\cd pipeline that push charts to that chartmuseum
3. There is developers show can install charts from it

Expect:
1. Have 2 different authentifications: one for `push` endpoints and one for `pull` endpoints.

Exists:
1. Single authentication for all api endpoints.

Why Important:
To restrict access between group of users who can publish charts (especially when it is enabled override mode) and users who can just install that charts.

Current workaround we use:
Run 2 instances on chartmuseum that share the same storage but have different authentication params.

**Comment by jdolitsky** [comment]
@goruha please discuss your needs regarding this on #59 

The plan right now is to accept JWT tokens, which have format similar to docker registry:
```
"access": [
    {
      "type": "repository",
      "name": "myorg/myrepo",
      "actions": [
        "push",
        "pull"
      ]
    }
  ]
```
